export const ORDER_STATUSES=['pending','checkout_created','paid','payment_failed','cancelled','refunded','partially_refunded'];
export const FULFILLMENT_STATUSES=['not_required','awaiting_campaign_close','ordered_from_vendor','ready_for_pickup','picked_up'];
export const codePattern=/^[A-Z0-9]{6}$/;
export const clean=value=>String(value??'').trim();
export const normalizeEmail=value=>clean(value).toLowerCase();
export const now=()=>new Date().toISOString();
export const id=prefix=>`${prefix}_${crypto.randomUUID().replaceAll('-','')}`;
export function validateShape(body){
  if(!body||!Array.isArray(body.items)||body.items.length<1||body.items.length>50)throw new Error('INVALID_ORDER');
  if(!body.customerContact||!clean(body.customerContact.firstName)||!clean(body.customerContact.lastName)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizeEmail(body.customerContact.email))||!clean(body.customerContact.phone))throw new Error('INVALID_CONTACT');
  for(const item of body.items){if(!/^[a-z0-9][a-z0-9-]{1,80}$/.test(clean(item.productId))||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99||!Array.isArray(item.optionIds))throw new Error('INVALID_ITEM');for(const option of item.optionIds)if(!/^[a-z0-9][a-z0-9-]{0,50}$/.test(clean(option.optionId))||!/^[a-z0-9][a-z0-9-]{0,80}$/.test(clean(option.valueId)))throw new Error('INVALID_OPTION');}
  const code=clean(body.fundraisingCode).toUpperCase();if(code&&!codePattern.test(code))throw new Error('INVALID_ATTRIBUTION');
  return {...body,campaignId:clean(body.campaignId)||null,fundraisingCode:code||null,pickupSelection:clean(body.pickupSelection)||null,attributionSource:clean(body.attributionSource).slice(0,64)||'pack-wide',sourcePage:clean(body.sourcePage).slice(0,200)||null,customerContact:{firstName:clean(body.customerContact.firstName).slice(0,80),lastName:clean(body.customerContact.lastName).slice(0,80),email:normalizeEmail(body.customerContact.email).slice(0,254),phone:clean(body.customerContact.phone).slice(0,40)}};
}
export async function sha256(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export async function verifyStripeSignature(raw,header,secret,tolerance=300,epoch=Math.floor(Date.now()/1000)){
  const parts=Object.fromEntries(String(header||'').split(',').map(part=>part.split('=')));const timestamp=Number(parts.t);if(!timestamp||!parts.v1||Math.abs(epoch-timestamp)>tolerance)return false;
  const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${raw}`));const expected=[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');if(expected.length!==parts.v1.length)return false;let mismatch=0;for(let i=0;i<expected.length;i++)mismatch|=expected.charCodeAt(i)^parts.v1.charCodeAt(i);return mismatch===0;
}
export function stripeForm(order,items,origin,packId){const form=new URLSearchParams({mode:'payment',client_reference_id:order.id,customer_email:order.customer_email,success_url:`${origin}/confirmation.html?order=${encodeURIComponent(order.order_number)}&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${origin}/cart.html?checkout=cancelled`,'metadata[internal_order_reference]':order.id,'metadata[campaign_id]':order.campaign_id||'','metadata[fundraising_code]':order.fundraising_code||'','metadata[attribution_type]':order.fundraising_code?'scout':'pack','metadata[source_page]':order.source_page||'storefront','metadata[pack_identifier]':packId});items.forEach((item,index)=>{form.set(`line_items[${index}][price_data][currency]`,item.currency);form.set(`line_items[${index}][price_data][unit_amount]`,String(item.unit_amount));form.set(`line_items[${index}][price_data][product_data][name]`,item.product_name);form.set(`line_items[${index}][quantity]`,String(item.quantity));});return form;}
