import {validateShape,sha256,verifyStripeSignature,stripeForm,id,now,FULFILLMENT_STATUSES} from './domain.mjs';
import {trustedCheckout,createPendingOrder,setCheckoutSession,orderView} from './repository.mjs';

const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const genericError=(status=400)=>json({error:'REQUEST_UNAVAILABLE',message:'We could not complete this request.'},status);
const cors=(env,request)=>{const origin=request.headers.get('origin');return origin&&origin===env.STOREFRONT_ORIGIN?{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,idempotency-key,authorization','access-control-max-age':'600','vary':'Origin'}:{}};
const ipKey=request=>request.headers.get('cf-connecting-ip')||'local';
async function limited(binding,key){if(!binding?.limit)return false;const result=await binding.limit({key});return !result.success;}
async function adminAuthorized(request,env){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'')||'';if(!token||!env.ADMIN_API_TOKEN)return false;return await sha256(token)===await sha256(env.ADMIN_API_TOKEN);}
const safeBody=async request=>{if(!String(request.headers.get('content-type')).includes('application/json'))throw new Error('INVALID_CONTENT_TYPE');const text=await request.text();if(text.length>50000)throw new Error('TOO_LARGE');return JSON.parse(text);};

async function createCheckout(request,env){
  if(await limited(env.CHECKOUT_RATE_LIMITER,ipKey(request)))return genericError(429);const key=request.headers.get('idempotency-key');if(!key||!/^[A-Za-z0-9_-]{16,100}$/.test(key))return genericError(400);
  try{
    const input=validateShape(await safeBody(request));const trusted=await trustedCheckout(env.DB,input);if(!env.STRIPE_SECRET_KEY?.startsWith('sk_test_'))return genericError(503);const checkoutKey=await sha256(`${key}.${input.customerContact.email}`);const pending=await createPendingOrder(env.DB,input,trusted,checkoutKey);if(pending.existing&&pending.order.stripe_checkout_url)return json({orderNumber:pending.order.order_number,checkoutUrl:pending.order.stripe_checkout_url,reused:true});
    const order={...pending.order,fundraising_code:input.fundraisingCode};const form=stripeForm(order,trusted.items,env.STOREFRONT_ORIGIN,env.PACK_ID);form.set('payment_intent_data[metadata][internal_order_reference]',order.id);let stripe;try{stripe=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'content-type':'application/x-www-form-urlencoded','idempotency-key':checkoutKey,...(env.STRIPE_API_VERSION?{'stripe-version':env.STRIPE_API_VERSION}:{})},body:form});}catch{return genericError(502);}const session=await stripe.json();if(!stripe.ok||!session.id||!session.url)return genericError(502);await setCheckoutSession(env.DB,order,session);return json({orderNumber:order.order_number,checkoutUrl:session.url,reused:pending.existing},pending.existing?200:201);
  }catch{return genericError(400);}
}

async function webhook(request,env){
  const raw=await request.text();const signature=request.headers.get('stripe-signature');if(!env.STRIPE_WEBHOOK_SECRET||!await verifyStripeSignature(raw,signature,env.STRIPE_WEBHOOK_SECRET))return genericError(400);let event;try{event=JSON.parse(raw);}catch{return genericError(400);}
  const duplicate=await env.DB.prepare('SELECT stripe_event_id FROM stripe_events WHERE stripe_event_id=?').bind(event.id).first();if(duplicate)return json({received:true,duplicate:true});
  const object=event.data?.object||{};const orderId=object.metadata?.internal_order_reference||object.client_reference_id;const order=orderId?await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(orderId).first():null;
  if(event.type==='checkout.session.completed'&&object.payment_status==='paid'&&order){const timestamp=now();await env.DB.batch([env.DB.prepare('INSERT INTO stripe_events(stripe_event_id,event_type,received_at) VALUES(?,?,?)').bind(event.id,event.type,timestamp),env.DB.prepare("UPDATE orders SET status='paid',paid_at=?,updated_at=? WHERE id=? AND status!='paid'").bind(timestamp,timestamp,order.id),env.DB.prepare("UPDATE inventory_reservations SET status='committed',updated_at=? WHERE order_id=? AND status='reserved'").bind(timestamp,order.id),env.DB.prepare('INSERT INTO payments(id,order_id,stripe_event_id,stripe_payment_intent_id,amount,currency,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id('pay'),order.id,event.id,object.payment_intent,object.amount_total||order.total_amount,object.currency||order.currency,'paid',timestamp,timestamp),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'payment.paid','stripe',JSON.stringify({eventId:event.id}),timestamp)]);return json({received:true});}
  if(['checkout.session.async_payment_failed','payment_intent.payment_failed'].includes(event.type)&&order){const timestamp=now();await env.DB.batch([env.DB.prepare('INSERT INTO stripe_events(stripe_event_id,event_type,received_at) VALUES(?,?,?)').bind(event.id,event.type,timestamp),env.DB.prepare("UPDATE orders SET status='payment_failed',updated_at=? WHERE id=? AND status NOT IN ('paid','refunded','partially_refunded')").bind(timestamp,order.id),env.DB.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE order_id=? AND status='reserved'").bind(timestamp,order.id),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'payment.failed','stripe',JSON.stringify({eventId:event.id}),timestamp)]);return json({received:true});}
  if(event.type==='charge.refunded'){const payment=await env.DB.prepare('SELECT * FROM payments WHERE stripe_payment_intent_id=? ORDER BY created_at DESC LIMIT 1').bind(object.payment_intent).first();if(payment){const status=object.amount_refunded<object.amount?'partially_refunded':'refunded';const timestamp=now();await env.DB.batch([env.DB.prepare('INSERT INTO stripe_events(stripe_event_id,event_type,received_at) VALUES(?,?,?)').bind(event.id,event.type,timestamp),env.DB.prepare('UPDATE orders SET status=?,updated_at=? WHERE id=?').bind(status,timestamp,payment.order_id),env.DB.prepare('UPDATE payments SET status=?,updated_at=? WHERE id=?').bind(status,timestamp,payment.id),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),payment.order_id,`payment.${status}`,'stripe',JSON.stringify({eventId:event.id,amountRefunded:object.amount_refunded}),timestamp)]);return json({received:true});}}
  await env.DB.prepare('INSERT INTO stripe_events(stripe_event_id,event_type,received_at) VALUES(?,?,?)').bind(event.id,event.type,now()).run();return json({received:true});
}

async function confirmation(url,env){const number=url.searchParams.get('order')||'';const sessionId=url.searchParams.get('session_id')||'';if(!number||!sessionId)return genericError(404);const order=await env.DB.prepare("SELECT * FROM orders WHERE order_number=? AND stripe_session_id=? AND status IN ('paid','refunded','partially_refunded')").bind(number,sessionId).first();if(!order)return genericError(404);return json(await orderView(env.DB,order));}

async function lookup(request,env){if(await limited(env.LOOKUP_RATE_LIMITER,ipKey(request)))return genericError(429);try{const body=await safeBody(request);const number=String(body.orderNumber||'').trim().toUpperCase();const email=String(body.email||'').trim().toLowerCase();const order=await env.DB.prepare("SELECT * FROM orders WHERE order_number=? AND customer_email_normalized=? AND status IN ('paid','refunded','partially_refunded')").bind(number,email).first();if(!order)return genericError(404);return json(await orderView(env.DB,order));}catch{return genericError(404);}}

const csv=value=>`"${String(value??'').replaceAll('"','""')}"`;
async function admin(request,url,env){if(await limited(env.ADMIN_RATE_LIMITER,ipKey(request)))return genericError(429);if(!await adminAuthorized(request,env))return genericError(401);const path=url.pathname;
  if(path==='/api/admin/orders'&&request.method==='GET'){const clauses=[];const values=[];for(const [param,column] of [['campaign','o.campaign_id'],['paymentStatus','o.status'],['fulfillmentStatus','o.fulfillment_status'],['scoutCode','a.fundraising_code']]){const value=url.searchParams.get(param);if(value){clauses.push(`${column}=?`);values.push(value);}}const search=url.searchParams.get('search');if(search){clauses.push('(o.order_number=? OR o.customer_email_normalized=?)');values.push(search.toUpperCase(),search.toLowerCase());}const where=clauses.length?`WHERE ${clauses.join(' AND ')}`:'';const {results}=await env.DB.prepare(`SELECT o.order_number,o.status,o.fulfillment_status,o.campaign_id,o.total_amount,o.currency,o.customer_email,o.created_at,a.fundraising_code FROM orders o LEFT JOIN scout_attribution a ON a.order_id=o.id ${where} ORDER BY o.created_at DESC LIMIT 250`).bind(...values).all();return json({orders:results});}
  if(path==='/api/admin/orders/export.csv'&&request.method==='GET'){const {results}=await env.DB.prepare('SELECT o.order_number,o.status,o.fulfillment_status,o.campaign_id,o.total_amount,o.currency,o.customer_email,o.created_at,a.fundraising_code FROM orders o LEFT JOIN scout_attribution a ON a.order_id=o.id ORDER BY o.created_at DESC LIMIT 5000').all();const header='order_number,status,fulfillment_status,campaign_id,total_amount,currency,customer_email,fundraising_code,created_at';const rows=results.map(row=>[row.order_number,row.status,row.fulfillment_status,row.campaign_id,row.total_amount,row.currency,row.customer_email,row.fundraising_code,row.created_at].map(csv).join(','));return new Response([header,...rows].join('\n'),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="pack321-orders.csv"','cache-control':'no-store'}});}
  const match=path.match(/^\/api\/admin\/orders\/([^/]+)(?:\/(ready-for-pickup|picked-up|attribution))?$/);if(!match)return genericError(404);const order=await env.DB.prepare('SELECT * FROM orders WHERE order_number=?').bind(decodeURIComponent(match[1]).toUpperCase()).first();if(!order)return genericError(404);if(request.method==='GET'&&!match[2])return json({...await orderView(env.DB,order),customerContact:{firstName:order.customer_first_name,lastName:order.customer_last_name,email:order.customer_email,phone:order.customer_phone}});if(request.method!=='POST'||!match[2])return genericError(405);const body=await safeBody(request);const actor=String(body.actor||'admin').slice(0,100);const timestamp=now();
  if(match[2]==='ready-for-pickup'||match[2]==='picked-up'){const target=match[2]==='ready-for-pickup'?'ready_for_pickup':'picked_up';if(!FULFILLMENT_STATUSES.includes(target))return genericError(400);await env.DB.batch([env.DB.prepare('UPDATE orders SET fulfillment_status=?,updated_at=? WHERE id=?').bind(target,timestamp,order.id),env.DB.prepare('INSERT INTO fulfillment_events(id,order_id,from_status,to_status,actor,note,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('fulfill'),order.id,order.fulfillment_status,target,actor,String(body.note||'').slice(0,500),timestamp),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,reason,details_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),order.id,`fulfillment.${target}`,actor,String(body.note||'').slice(0,500),'{}',timestamp)]);return json({updated:true,fulfillmentStatus:target});}
  const code=String(body.fundraisingCode||'').trim().toUpperCase();const reason=String(body.reason||'').trim();if(!reason||reason.length<5)return genericError(400);if(code){const eligible=await env.DB.prepare("SELECT s.fundraising_code FROM public_scout_profiles s JOIN scout_campaigns sc ON sc.fundraising_code=s.fundraising_code WHERE s.fundraising_code=? AND s.active=1 AND s.visibility='public' AND s.guardian_approved=1 AND sc.campaign_id=? AND sc.active=1").bind(code,order.campaign_id).first();if(!eligible)return genericError(400);}const previous=await env.DB.prepare('SELECT fundraising_code FROM scout_attribution WHERE order_id=? ORDER BY created_at DESC LIMIT 1').bind(order.id).first();await env.DB.batch([env.DB.prepare('INSERT INTO scout_attribution(id,order_id,fundraising_code,attribution_type,source_page,corrected_from_code,correction_reason,corrected_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(id('attr'),order.id,code||null,code?'scout':'pack','admin-correction',previous?.fundraising_code||null,reason,actor,timestamp),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,reason,details_json,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),order.id,'attribution.corrected',actor,reason,JSON.stringify({from:previous?.fundraising_code||null,to:code||null}),timestamp)]);return json({updated:true});
}

async function cancelAbandoned(env){const {results}=await env.DB.prepare("SELECT id FROM orders WHERE status IN ('pending','checkout_created') AND datetime(updated_at)<datetime('now','-24 hours') LIMIT 200").all();if(!results.length)return;const timestamp=now();await env.DB.batch(results.flatMap(order=>[env.DB.prepare("UPDATE orders SET status='cancelled',updated_at=? WHERE id=? AND status IN ('pending','checkout_created')").bind(timestamp,order.id),env.DB.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE order_id=? AND status='reserved'").bind(timestamp,order.id),env.DB.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'checkout.abandoned','system','{}',timestamp)]));}

export default {async fetch(request,env){const url=new URL(request.url);const headers=cors(env,request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});let response;if(url.pathname==='/api/checkout-sessions'&&request.method==='POST')response=await createCheckout(request,env);else if(url.pathname==='/api/stripe/webhook'&&request.method==='POST')response=await webhook(request,env);else if(url.pathname==='/api/confirmation'&&request.method==='GET')response=await confirmation(url,env);else if(url.pathname==='/api/order-lookup'&&request.method==='POST')response=await lookup(request,env);else if(url.pathname.startsWith('/api/admin/'))response=await admin(request,url,env);else if(url.pathname==='/health')response=json({ok:true,service:'pack321-storefront-api'});else response=genericError(404);for(const [key,value] of Object.entries(headers))response.headers.set(key,value);return response;},async scheduled(controller,env,ctx){ctx.waitUntil(cancelAbandoned(env));}};
