import {accounting,id,now,publicOrderNumber} from './domain.mjs';

export async function trustedCheckout(db,request){
  const ids=[...new Set(request.items.map(item=>item.productId))];const marks=ids.map(()=>'?').join(',');
  const {results:products}=await db.prepare(`SELECT p.*,c.name campaign_name,c.campaign_type,c.status campaign_status,c.visibility campaign_visibility,c.starts_at,c.ends_at,c.fulfillment_promise,c.pickup_instructions campaign_pickup_instructions FROM products p LEFT JOIN campaigns c ON c.id=p.campaign_id WHERE p.id IN (${marks})`).bind(...ids).all();if(products.length!==ids.length)throw new Error('INVALID_PRODUCT');
  const byId=Object.fromEntries(products.map(product=>[product.id,product]));const trusted=[];let subtotal=0;let pickupRequired=false;const campaignIds=new Set();const localPickupCampaignIds=new Set();
  for(const item of request.items){
    const product=byId[item.productId];if(!product.active||product.price_status!=='approved'||product.unit_amount<=0||product.inventory_mode==='sold_out')throw new Error('PRODUCT_UNAVAILABLE');
    if(product.campaign_id){if(product.campaign_status!=='active'||product.campaign_visibility!=='public'||(product.starts_at&&new Date(product.starts_at)>new Date())||(product.ends_at&&new Date(product.ends_at)<new Date()))throw new Error('CAMPAIGN_UNAVAILABLE');campaignIds.add(product.campaign_id);}
    if(product.inventory_mode==='tracked'&&Number(product.inventory_quantity)<item.quantity)throw new Error('PRODUCT_UNAVAILABLE');
    const {results:allowed}=await db.prepare('SELECT option_id,value_id,required FROM product_options WHERE product_id=? AND active=1').bind(product.id).all();const selected=new Map(item.optionIds.map(option=>[option.optionId,option.valueId]));for(const option of item.optionIds)if(!allowed.some(row=>row.option_id===option.optionId&&row.value_id===option.valueId))throw new Error('INVALID_OPTION');for(const optionId of new Set(allowed.filter(row=>row.required).map(row=>row.option_id)))if(!selected.has(optionId))throw new Error('MISSING_OPTION');
    const line=product.unit_amount*item.quantity;subtotal+=line;pickupRequired||=product.fulfillment_type==='local-pickup';if(product.fulfillment_type==='local-pickup'&&product.campaign_id)localPickupCampaignIds.add(product.campaign_id);trusted.push({product_id:product.id,product_name:product.name,product_sku:product.sku,unit_amount:product.unit_amount,currency:product.currency,quantity:item.quantity,line_amount:line,option_ids:item.optionIds,fulfillment_type:product.fulfillment_type,campaign_id:product.campaign_id,campaign_name:product.campaign_name,campaign_type:product.campaign_type,campaign_fulfillment_promise:product.fulfillment_promise,pickup_instructions:product.campaign_pickup_instructions,scout_credit_eligible:Boolean(product.campaign_id)&&product.fulfillment_type!=='none'});
  }
  if(subtotal<50||subtotal>1000000)throw new Error('INVALID_TOTAL');const currency=trusted[0].currency;if(trusted.some(item=>item.currency!==currency))throw new Error('MIXED_CURRENCY');
  let pickup=null;if(pickupRequired){pickup=await db.prepare(`SELECT p.id,p.name,COALESCE(p.instructions,group_concat(DISTINCT c.pickup_instructions)) instructions FROM pickup_locations p JOIN campaign_pickup_locations cp ON cp.pickup_location_id=p.id JOIN campaigns c ON c.id=cp.campaign_id WHERE p.id=? AND p.active=1 AND cp.campaign_id IN (${[...localPickupCampaignIds].map(()=>'?').join(',')}) GROUP BY p.id,p.name,p.instructions HAVING COUNT(DISTINCT cp.campaign_id)=?`).bind(request.pickupSelection,...localPickupCampaignIds,localPickupCampaignIds.size).first();if(!pickup)throw new Error('INVALID_PICKUP');}else if(request.pickupSelection)throw new Error('PICKUP_NOT_REQUIRED');
  let scout=null;if(request.fundraisingCode){for(const campaignId of campaignIds){const eligible=await db.prepare("SELECT s.fundraising_code,s.public_display_name FROM public_scout_profiles s JOIN scout_campaigns sc ON sc.fundraising_code=s.fundraising_code WHERE s.fundraising_code=? AND s.active=1 AND s.visibility='public' AND s.guardian_approved=1 AND (s.expires_at IS NULL OR datetime(s.expires_at)>datetime('now')) AND sc.campaign_id=? AND sc.active=1").bind(request.fundraisingCode,campaignId).first();if(!eligible)throw new Error('ATTRIBUTION_UNAVAILABLE');scout=eligible;}}
  const totals=accounting(subtotal);const campaignNames=[...new Set(trusted.map(item=>item.campaign_name).filter(Boolean))];const campaignTypes=[...new Set(trusted.map(item=>item.campaign_type).filter(Boolean))];const fulfillmentTypes=[...new Set(trusted.map(item=>item.fulfillment_type))];for(const item of trusted)item.scout_credit_amount=request.fundraisingCode&&item.scout_credit_eligible?item.line_amount:0;
  return {items:trusted,...totals,currency,pickupRequired,pickup,campaignId:campaignIds.size===1?[...campaignIds][0]:null,campaignName:campaignNames.length===1?campaignNames[0]:'Mixed / Pack-wide',campaignType:campaignTypes.length===1?campaignTypes[0]:'mixed',fulfillmentTypes,fulfillmentSummary:fulfillmentTypes.join(','),scout,scoutCreditAmount:trusted.reduce((sum,item)=>sum+item.scout_credit_amount,0)};
}

export async function createPendingOrder(db,request,trusted,fingerprint){
  const existing=await db.prepare('SELECT * FROM orders WHERE checkout_fingerprint=?').bind(fingerprint).first();if(existing)return{existing:true,order:existing};
  for(let attempt=0;attempt<5;attempt++){
    const created=now();const orderId=id('ord');const orderNumber=publicOrderNumber();const attributionType=request.fundraisingCode?'scout':'pack';const displayText=request.fundraisingCode?`Supporting ${trusted.scout?.public_display_name||'a Pack 321 Scout'}`:'Supporting Pack 321 generally';const fulfillment=trusted.pickupRequired?'awaiting_campaign_close':'not_required';
    const order={id:orderId,order_number:orderNumber,checkout_fingerprint:fingerprint,status:'pending',payment_status:'unpaid',fulfillment_status:fulfillment,campaign_id:trusted.campaignId,campaign_name:trusted.campaignName,campaign_type:trusted.campaignType,currency:trusted.currency,subtotal_amount:trusted.subtotalAmount,tax_amount:trusted.taxAmount,customer_fee_amount:trusted.customerFeeAmount,gross_amount:trusted.grossAmount,stripe_fee_amount:0,refund_amount:0,net_amount:trusted.netAmount,scout_credit_amount:trusted.scoutCreditAmount,customer_first_name:request.customerContact.firstName,customer_last_name:request.customerContact.lastName,customer_email:request.customerContact.email,customer_email_normalized:request.customerContact.email,customer_phone:request.customerContact.phone,pickup_location_id:trusted.pickup?.id||null,pickup_location_name:trusted.pickup?.name||null,pickup_instructions:trusted.pickup?.instructions||null,attribution_type:attributionType,scout_attribution_ref:request.fundraisingCode,attribution_display_text:displayText,attribution_source:request.attributionSource,source_page:request.sourcePage,created_at:created,updated_at:created,fulfillment_summary:trusted.fulfillmentSummary};
    const statements=[db.prepare('INSERT INTO orders(id,order_number,checkout_fingerprint,status,payment_status,fulfillment_status,campaign_id,campaign_name,campaign_type,currency,subtotal_amount,tax_amount,customer_fee_amount,gross_amount,stripe_fee_amount,refund_amount,net_amount,scout_credit_amount,customer_first_name,customer_last_name,customer_email,customer_email_normalized,customer_phone,pickup_location_id,pickup_location_name,pickup_instructions,attribution_type,scout_attribution_ref,attribution_display_text,attribution_source,source_page,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(order.id,order.order_number,order.checkout_fingerprint,order.status,order.payment_status,order.fulfillment_status,order.campaign_id,order.campaign_name,order.campaign_type,order.currency,order.subtotal_amount,order.tax_amount,order.customer_fee_amount,order.gross_amount,order.stripe_fee_amount,order.refund_amount,order.net_amount,order.scout_credit_amount,order.customer_first_name,order.customer_last_name,order.customer_email,order.customer_email_normalized,order.customer_phone,order.pickup_location_id,order.pickup_location_name,order.pickup_instructions,order.attribution_type,order.scout_attribution_ref,order.attribution_display_text,order.attribution_source,order.source_page,created,created),...trusted.items.map(item=>db.prepare('INSERT INTO order_items(id,order_id,product_id,product_name,product_sku,unit_amount,quantity,line_amount,fulfillment_type,campaign_id,campaign_name,campaign_type,campaign_fulfillment_promise,pickup_location_id,pickup_location_name,pickup_instructions,scout_credit_eligible,scout_credit_amount,option_ids_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id('item'),order.id,item.product_id,item.product_name,item.product_sku,item.unit_amount,item.quantity,item.line_amount,item.fulfillment_type,item.campaign_id,item.campaign_name,item.campaign_type,item.campaign_fulfillment_promise,item.fulfillment_type==='local-pickup'?order.pickup_location_id:null,item.fulfillment_type==='local-pickup'?order.pickup_location_name:null,item.fulfillment_type==='local-pickup'?(order.pickup_instructions||item.pickup_instructions):item.pickup_instructions,item.scout_credit_eligible?1:0,item.scout_credit_amount,JSON.stringify(item.option_ids))),db.prepare('INSERT INTO scout_attribution(id,order_id,fundraising_code,attribution_type,display_text,source_page,created_at) VALUES(?,?,?,?,?,?,?)').bind(id('attr'),order.id,request.fundraisingCode,attributionType,displayText,request.sourcePage,created),db.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'order.created','customer',JSON.stringify({subtotal:order.subtotal_amount,fee:order.customer_fee_amount,tax:order.tax_amount,gross:order.gross_amount}),created)];
    try{await db.batch(statements);return{existing:false,order};}catch(error){const raced=await db.prepare('SELECT * FROM orders WHERE checkout_fingerprint=?').bind(fingerprint).first();if(raced)return{existing:true,order:raced};if(attempt===4)throw error;}
  }
}

export async function beginPaymentAttempt(db,order,fingerprint){const timestamp=now();await db.prepare('INSERT INTO payment_attempts(id,order_id,request_fingerprint,amount,currency,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(request_fingerprint) DO UPDATE SET updated_at=excluded.updated_at').bind(id('attempt'),order.id,fingerprint,order.gross_amount,order.currency,'creating',timestamp,timestamp).run();}
export async function setCheckoutSession(db,order,session,fingerprint){const updated=now();await db.batch([db.prepare("UPDATE orders SET status='checkout_created',payment_status='pending',stripe_session_id=?,stripe_checkout_url=?,stripe_session_expires_at=?,updated_at=? WHERE id=? AND status IN ('pending','payment_failed')").bind(session.id,session.url,session.expires_at?new Date(session.expires_at*1000).toISOString():null,updated,order.id),db.prepare("UPDATE payment_attempts SET stripe_session_id=?,status='open',updated_at=? WHERE request_fingerprint=?").bind(session.id,updated,fingerprint),db.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'checkout.created','system',JSON.stringify({stripeSessionId:session.id}),updated)]);}

export async function orderView(db,order){const {results:items}=await db.prepare('SELECT product_name,quantity,line_amount,fulfillment_type,pickup_location_name,pickup_instructions,option_ids_json FROM order_items WHERE order_id=? ORDER BY rowid').bind(order.id).all();const {results:refunds}=await db.prepare("SELECT amount,eligible_merchandise_amount,customer_fee_refund_amount,category,attribution_adjustment_amount,reason,status,created_at FROM refunds WHERE order_id=? AND status IN ('pending','succeeded') ORDER BY created_at").bind(order.id).all();return{orderNumber:order.order_number,status:order.status,paymentStatus:order.payment_status,fulfillmentStatus:order.fulfillment_status,currency:order.currency,subtotalAmount:order.subtotal_amount,taxAmount:order.tax_amount,customerFeeAmount:order.customer_fee_amount,grossAmount:order.gross_amount,refundAmount:order.refund_amount,netAmount:order.net_amount,pickupName:order.pickup_location_name,pickupInstructions:order.pickup_instructions,attributionText:order.attribution_display_text,supportContact:'Pack 321 leadership via pack321wi.org/contact/',createdAt:order.created_at,paidAt:order.paid_at,items:items.map(item=>({productName:item.product_name,quantity:item.quantity,lineAmount:item.line_amount,fulfillmentType:item.fulfillment_type,pickupName:item.pickup_location_name,pickupInstructions:item.pickup_instructions,optionIds:JSON.parse(item.option_ids_json)})),refunds};}
