import {id,now,sha256} from './domain.mjs';

export async function trustedCheckout(db,request){
  const ids=[...new Set(request.items.map(item=>item.productId))];const marks=ids.map(()=>'?').join(',');
  const {results:products}=await db.prepare(`SELECT * FROM products WHERE id IN (${marks})`).bind(...ids).all();if(products.length!==ids.length)throw new Error('INVALID_PRODUCT');
  const byId=Object.fromEntries(products.map(product=>[product.id,product]));const campaignIds=[...new Set(products.map(product=>product.campaign_id).filter(Boolean))];if(campaignIds.length>1||campaignIds[0]!==request.campaignId)throw new Error('INVALID_CAMPAIGN');
  let campaign=null;if(request.campaignId){campaign=await db.prepare("SELECT * FROM campaigns WHERE id=? AND status='active' AND visibility='public' AND (starts_at IS NULL OR date(starts_at)<=date('now')) AND (ends_at IS NULL OR date(ends_at)>=date('now'))").bind(request.campaignId).first();if(!campaign)throw new Error('CAMPAIGN_UNAVAILABLE');}
  const trusted=[];let total=0;let pickupRequired=false;
  for(const item of request.items){const product=byId[item.productId];let available=product.inventory_quantity;if(product.inventory_mode==='tracked'){const reserved=await db.prepare("SELECT COALESCE(SUM(quantity),0) AS quantity FROM inventory_reservations WHERE product_id=? AND status='reserved'").bind(product.id).first();available-=Number(reserved?.quantity||0);}if(!product.active||product.inventory_mode==='sold_out'||(product.inventory_mode==='tracked'&&available<item.quantity))throw new Error('PRODUCT_UNAVAILABLE');
    const {results:allowed}=await db.prepare('SELECT option_id,value_id,required FROM product_options WHERE product_id=? AND active=1').bind(product.id).all();const selected=new Map(item.optionIds.map(option=>[option.optionId,option.valueId]));for(const option of item.optionIds)if(!allowed.some(row=>row.option_id===option.optionId&&row.value_id===option.valueId))throw new Error('INVALID_OPTION');for(const optionId of new Set(allowed.filter(row=>row.required).map(row=>row.option_id)))if(!selected.has(optionId))throw new Error('MISSING_OPTION');
    const line=product.unit_amount*item.quantity;total+=line;pickupRequired ||= Boolean(product.pickup_required);trusted.push({product_id:product.id,product_name:product.name,unit_amount:product.unit_amount,currency:product.currency,quantity:item.quantity,line_amount:line,option_ids:item.optionIds,inventory_mode:product.inventory_mode});}
  if(total<50||total>1000000)throw new Error('INVALID_TOTAL');const currency=trusted[0].currency;if(trusted.some(item=>item.currency!==currency))throw new Error('MIXED_CURRENCY');
  if(pickupRequired){const pickup=await db.prepare('SELECT p.id FROM pickup_locations p JOIN campaign_pickup_locations cp ON cp.pickup_location_id=p.id WHERE p.id=? AND p.active=1 AND cp.campaign_id=?').bind(request.pickupSelection,request.campaignId).first();if(!pickup)throw new Error('INVALID_PICKUP');}else if(request.pickupSelection){const pickup=await db.prepare('SELECT id FROM pickup_locations WHERE id=? AND active=1').bind(request.pickupSelection).first();if(!pickup)throw new Error('INVALID_PICKUP');}
  let scout=null;if(request.fundraisingCode){scout=await db.prepare("SELECT s.fundraising_code FROM public_scout_profiles s JOIN scout_campaigns sc ON sc.fundraising_code=s.fundraising_code WHERE s.fundraising_code=? AND s.active=1 AND s.visibility='public' AND s.guardian_approved=1 AND (s.expires_at IS NULL OR datetime(s.expires_at)>datetime('now')) AND sc.campaign_id=? AND sc.active=1").bind(request.fundraisingCode,request.campaignId).first();if(!scout)throw new Error('ATTRIBUTION_UNAVAILABLE');}
  return {campaign,items:trusted,total,currency,pickupRequired};
}

export async function createPendingOrder(db,request,trusted,checkoutKey){
  const existing=await db.prepare('SELECT * FROM orders WHERE checkout_key=?').bind(checkoutKey).first();if(existing)return{existing:true,order:existing};
  const created=now();const orderId=id('ord');const orderNumber=`P321-${created.slice(2,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const fulfillment=trusted.pickupRequired?'awaiting_campaign_close':'not_required';
  const order={id:orderId,order_number:orderNumber,status:'pending',fulfillment_status:fulfillment,campaign_id:request.campaignId,currency:trusted.currency,subtotal_amount:trusted.total,total_amount:trusted.total,customer_first_name:request.customerContact.firstName,customer_last_name:request.customerContact.lastName,customer_email:request.customerContact.email,customer_email_normalized:request.customerContact.email,customer_phone:request.customerContact.phone,pickup_location_id:request.pickupSelection,attribution_source:request.attributionSource,source_page:request.sourcePage,checkout_key:checkoutKey,created_at:created,updated_at:created,fundraising_code:request.fundraisingCode};
  const statements=[db.prepare('INSERT INTO orders(id,order_number,status,fulfillment_status,campaign_id,currency,subtotal_amount,total_amount,customer_first_name,customer_last_name,customer_email,customer_email_normalized,customer_phone,pickup_location_id,attribution_source,source_page,checkout_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(order.id,order.order_number,order.status,order.fulfillment_status,order.campaign_id,order.currency,order.subtotal_amount,order.total_amount,order.customer_first_name,order.customer_last_name,order.customer_email,order.customer_email_normalized,order.customer_phone,order.pickup_location_id,order.attribution_source,order.source_page,order.checkout_key,created,created),...trusted.items.map(item=>db.prepare('INSERT INTO order_items(id,order_id,product_id,product_name,unit_amount,quantity,line_amount,option_ids_json) VALUES(?,?,?,?,?,?,?,?)').bind(id('item'),order.id,item.product_id,item.product_name,item.unit_amount,item.quantity,item.line_amount,JSON.stringify(item.option_ids))),...trusted.items.filter(item=>item.inventory_mode==='tracked').map(item=>db.prepare('INSERT INTO inventory_reservations(id,order_id,product_id,quantity,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id('reserve'),order.id,item.product_id,item.quantity,'reserved',created,created)),db.prepare('INSERT INTO scout_attribution(id,order_id,fundraising_code,attribution_type,source_page,created_at) VALUES(?,?,?,?,?,?)').bind(id('attr'),order.id,request.fundraisingCode,request.fundraisingCode?'scout':'pack',request.sourcePage,created),db.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'order.created','customer','{}',created)];await db.batch(statements);return{existing:false,order};
}

export async function setCheckoutSession(db,order,session){const updated=now();await db.batch([db.prepare("UPDATE orders SET status='checkout_created',stripe_session_id=?,stripe_checkout_url=?,updated_at=? WHERE id=? AND status IN ('pending','payment_failed')").bind(session.id,session.url,updated,order.id),db.prepare('INSERT INTO order_audit_log(id,order_id,action,actor,details_json,created_at) VALUES(?,?,?,?,?,?)').bind(id('audit'),order.id,'checkout.created','system',JSON.stringify({stripeSessionId:session.id}),updated)]);}

export async function orderView(db,order){const {results:items}=await db.prepare('SELECT product_name,quantity,line_amount,option_ids_json FROM order_items WHERE order_id=? ORDER BY rowid').bind(order.id).all();return{orderNumber:order.order_number,status:order.status,fulfillmentStatus:order.fulfillment_status,campaignId:order.campaign_id,currency:order.currency,totalAmount:order.total_amount,pickupSelection:order.pickup_location_id,createdAt:order.created_at,paidAt:order.paid_at,items:items.map(item=>({productName:item.product_name,quantity:item.quantity,lineAmount:item.line_amount,optionIds:JSON.parse(item.option_ids_json)}))};}
