import assert from 'node:assert/strict';
import {validateShape,verifyStripeSignature,stripeForm} from '../src/domain.mjs';
import {trustedCheckout} from '../src/repository.mjs';

const base={items:[{productId:'classic-holiday-wreath',optionIds:[],quantity:1,price:1}],campaignId:'wreaths-2026',fundraisingCode:'AB12CD',attributionSource:'code-search',pickupSelection:'carollton-elementary',sourcePage:'/scout/AB12CD',customerContact:{firstName:'Pat',lastName:'Example',email:'PAT@example.test',phone:'555-0100'},total:1};
const clean=validateShape(base);assert.equal(clean.customerContact.email,'pat@example.test');assert.equal(clean.fundraisingCode,'AB12CD');
assert.throws(()=>validateShape({...base,items:[{productId:'bad!',optionIds:[],quantity:1}]}),/INVALID_ITEM/);
assert.throws(()=>validateShape({...base,fundraisingCode:'bad code'}),/INVALID_ATTRIBUTION/);

const raw=JSON.stringify({id:'evt_test'});const secret='whsec_test_secret';const timestamp=Math.floor(Date.now()/1000);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${raw}`));const signature=[...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('');assert.equal(await verifyStripeSignature(raw,`t=${timestamp},v1=${signature}`,secret),true);assert.equal(await verifyStripeSignature(raw,`t=${timestamp-1000},v1=${signature}`,secret),false);assert.equal(await verifyStripeSignature(`${raw}x`,`t=${timestamp},v1=${signature}`,secret),false);

class FakeDB{constructor(mode='ok'){this.mode=mode;}prepare(sql){const db=this;return{args:[],bind(...args){this.args=args;return this;},async all(){if(sql.includes('FROM products WHERE'))return{results:db.mode==='invalid-product'?[]:[{id:'classic-holiday-wreath',campaign_id:'wreaths-2026',name:'Classic Holiday Wreath',unit_amount:3500,currency:'usd',active:1,inventory_mode:'preorder',inventory_quantity:null,pickup_required:1}]};if(sql.includes('FROM product_options'))return{results:[]};return{results:[]};},async first(){if(sql.includes('FROM campaigns'))return db.mode==='closed'?null:{id:'wreaths-2026',status:'active'};if(sql.includes('pickup_locations'))return{id:'carollton-elementary'};if(sql.includes('public_scout_profiles'))return db.mode==='inactive-scout'?null:{fundraising_code:'AB12CD'};return null;}};}}
const trusted=await trustedCheckout(new FakeDB(),clean);assert.equal(trusted.total,3500);assert.equal(trusted.items[0].unit_amount,3500);assert.rejects(()=>trustedCheckout(new FakeDB('invalid-product'),clean),/INVALID_PRODUCT/);assert.rejects(()=>trustedCheckout(new FakeDB('closed'),clean),/CAMPAIGN_UNAVAILABLE/);assert.rejects(()=>trustedCheckout(new FakeDB('inactive-scout'),clean),/ATTRIBUTION_UNAVAILABLE/);const pack=await trustedCheckout(new FakeDB(),{...clean,fundraisingCode:null});assert.equal(pack.total,3500);
const form=stripeForm({id:'ord_test',customer_email:'pat@example.test',order_number:'P321-TEST',campaign_id:'wreaths-2026',fundraising_code:'AB12CD',source_page:'/scout/AB12CD'},trusted.items,'https://store.example','pack-321');assert.equal(form.get('line_items[0][price_data][unit_amount]'),'3500');assert.equal(form.get('metadata[internal_order_reference]'),'ord_test');assert.match(form.get('success_url'),/\{CHECKOUT_SESSION_ID\}/);assert.equal(form.has('total'),false);

const workerSource=await (await import('node:fs/promises')).readFile(new URL('../src/index.mjs',import.meta.url),'utf8');assert.match(workerSource,/SELECT stripe_event_id FROM stripe_events/);assert.match(workerSource,/INSERT INTO stripe_events/);assert.match(workerSource,/status='paid'/);assert.match(workerSource,/charge\.refunded/);assert.match(workerSource,/checkout\.abandoned/);assert.match(workerSource,/inventory_reservations/);assert.doesNotMatch(workerSource,/console\.(?:log|info|warn|error)/);
console.log('Worker domain, trust-boundary, signature, campaign, attribution, refund, and duplicate-event tests passed.');
