import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {accounting,checkoutFingerprint,publicOrderNumber,refundDecision,stripeForm,validateShape,verifyStripeSignature} from '../src/domain.mjs';
import {createPendingOrder} from '../src/repository.mjs';
import {claimStripeEvent} from '../src/index.mjs';

const totals=accounting(5000,183,1000);assert.deepEqual(totals,{subtotalAmount:5000,taxAmount:0,customerFeeAmount:300,grossAmount:5300,stripeFeeAmount:183,refundAmount:1000,netAmount:4117});
assert.equal(refundDecision('customer_requested_partial',500,5000).customerFeeRefundAmount,0);assert.equal(refundDecision('pack_unfulfillable',5000,5000).customerFeeRefundAmount,300);
assert.match(publicOrderNumber(new Date('2026-08-07T12:00:00Z'),new Uint8Array([1,2,3,4,5])),/^P321-20260807-[0-9A-HJKMNP-TV-Z]{8}$/);
const shape={items:[{productId:'candy-bar',quantity:2,optionIds:[]}],fundraisingCode:null,pickupSelection:'school',attributionSource:'pack-wide',sourcePage:'/checkout',customerContact:{firstName:'Pat',lastName:'Example',email:'PAT@example.test',phone:'555-0100'}};
const cleaned=validateShape(shape);assert.equal(cleaned.customerContact.email,'pat@example.test');assert.throws(()=>validateShape({...shape,items:[{...shape.items[0],price:1}]}),/CLIENT_PRICE_REJECTED/);assert.equal(await checkoutFingerprint('a'.repeat(16),cleaned),await checkoutFingerprint('a'.repeat(16),cleaned));
const order={order_number:'P321-20260807-7K4M9Q2D',customer_email:'pat@example.test',campaign_id:'candy',attribution_type:'scout',scout_attribution_ref:'AB12CD',source_page:'/scout/AB12CD',fulfillment_summary:'local-pickup,program-direct-shipment',currency:'usd'};
const form=stripeForm(order,[{currency:'usd',unit_amount:2500,product_name:'Candy',quantity:2}],'https://test-shop.example','pack-321');assert.equal(form.get('line_items[0][price_data][unit_amount]'),'2500');assert.equal(form.get('line_items[1][price_data][unit_amount]'),'300');assert.equal(form.get('metadata[order_number]'),order.order_number);assert.equal(form.has('metadata[internal_order_reference]'),false);assert.equal(form.get('client_reference_id'),order.order_number);

const raw=JSON.stringify({id:'evt_1'});const secret='whsec_test';const timestamp=Math.floor(Date.now()/1000);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const bytes=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${raw}`));const good=[...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,'0')).join('');assert.equal(await verifyStripeSignature(raw,`t=${timestamp},v1=bad,v1=${good}`,secret),true);assert.equal(await verifyStripeSignature(raw,'malformed',secret),false);assert.equal(await verifyStripeSignature(raw,`t=${timestamp-301},v1=${good}`,secret),false);

class Statement{constructor(db,sql){this.db=db;this.sql=sql;this.args=[];}bind(...args){this.args=args;return this;}async first(){if(this.sql.includes('checkout_fingerprint'))return this.db.order?.checkout_fingerprint===this.args[0]?this.db.order:null;if(this.sql.includes('processing_status'))return this.db.events.get(this.args[0])?{processing_status:this.db.events.get(this.args[0])}:null;return null;}async run(){if(this.sql.startsWith('INSERT INTO stripe_events')){if(this.db.events.has(this.args[0]))throw new Error('UNIQUE');this.db.events.set(this.args[0],'claimed');return{meta:{changes:1}};}if(this.sql.startsWith('UPDATE stripe_events')){if(this.db.events.get(this.args[0])!=='failed')return{meta:{changes:0}};this.db.events.set(this.args[0],'claimed');return{meta:{changes:1}};}return{meta:{changes:1}};}}
class AtomicDB{constructor(){this.order=null;this.events=new Map();}prepare(sql){return new Statement(this,sql);}async batch(statements){await new Promise(resolve=>setTimeout(resolve,5));const insert=statements.find(statement=>statement.sql.startsWith('INSERT INTO orders'));const fingerprint=insert.args[2];if(this.order)throw new Error('UNIQUE');this.order={id:insert.args[0],order_number:insert.args[1],checkout_fingerprint:fingerprint,status:'pending'};return statements.map(()=>({meta:{changes:1}}));}}
const db=new AtomicDB();const trusted={items:[{product_id:'candy-bar',product_name:'Candy',product_sku:null,unit_amount:250,currency:'usd',quantity:2,line_amount:500,fulfillment_type:'local-pickup',campaign_id:'candy',campaign_name:'Candy',campaign_type:'candy-builder',campaign_fulfillment_promise:'Pickup',pickup_instructions:'Later',scout_credit_eligible:true,scout_credit_amount:500,option_ids:[]}],campaignId:'candy',campaignName:'Candy',campaignType:'candy-builder',currency:'usd',subtotalAmount:500,taxAmount:0,customerFeeAmount:300,grossAmount:800,netAmount:800,scoutCreditAmount:0,pickup:{id:'school',name:'School',instructions:'Later'},pickupRequired:true,fulfillmentSummary:'local-pickup'};
const fingerprint=await checkoutFingerprint('b'.repeat(16),cleaned);const concurrent=await Promise.all([createPendingOrder(db,cleaned,trusted,fingerprint),createPendingOrder(db,cleaned,trusted,fingerprint)]);assert.equal(new Set(concurrent.map(result=>result.order.order_number)).size,1);assert.equal(concurrent.filter(result=>result.existing).length,1);
const eventDb=new AtomicDB();const claims=await Promise.all([claimStripeEvent(eventDb,{id:'evt_atomic',type:'checkout.session.completed'}),claimStripeEvent(eventDb,{id:'evt_atomic',type:'checkout.session.completed'})]);assert.deepEqual(claims.sort(),[false,true]);

const catalogReport=JSON.parse(execFileSync(process.execPath,['scripts/sync-commerce-catalog.js','--dry-run'],{cwd:new URL('../..',import.meta.url),encoding:'utf8'}));assert.equal(catalogReport.ok,true);assert(catalogReport.pricingPendingProducts>0);assert.equal(catalogReport.violations.length,0);
const schema=await readFile(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8');for(const expected of ['customer_fee_amount','stripe_fee_amount','refund_amount','net_amount','payment_attempts','attribution_adjustments','fulfillment_type','payment-reconciliation-required'])assert.match(schema,new RegExp(expected));
const reportingSchema=await readFile(new URL('../migrations/0005_payment_finance_reporting.sql',import.meta.url),'utf8');for(const expected of ['payments','stripe_payment_intent_id','stripe_balance_transaction_id','card_brand','card_last4','funding_type','finance_posting_references','scout_credit_amount'])assert.match(reportingSchema,new RegExp(expected));
const refundRequestSchema=await readFile(new URL('../migrations/0006_authorized_refund_requests.sql',import.meta.url),'utf8');assert.match(refundRequestSchema,/CREATE TABLE refund_requests/);assert.match(refundRequestSchema,/UNIQUE\(order_id, category, merchandise_refund_amount, reason\)/);
const source=await readFile(new URL('../src/index.mjs',import.meta.url),'utf8');assert.match(source,/ACCESS_TEAM_DOMAIN/);assert.match(source,/payment-reconciliation-required/);assert.match(source,/checkout\/sessions\/.*\/expire/);assert.doesNotMatch(source,/ADMIN_API_TOKEN/);
assert.match(source,/payment\.fee_reconciled/);assert.match(source,/reconcilePaymentFees/);
assert.match(source,/processAuthorizedRefundRequests/);assert.match(source,/authorized-refund-request/);
console.log('Phase 1B accounting, order number, pricing boundary, idempotency, webhook claim, signature, catalog, Access, and reconciliation tests passed.');
