(function(){
  'use strict';
  const stat=(value,label)=>`<div class="stat"><strong>${value}</strong><span>${label}</span></div>`;
  const mediaKey=campaign=>campaign.templateId==='holiday-wreaths'?'holiday-wreaths':campaign.templateId;
  document.addEventListener('DOMContentLoaded',async()=>{
    const host=document.querySelector('[data-campaign-page]');if(!host)return;
    try{
      const [campaigns,products,locations,manifest]=await Promise.all([StoreUtils.loadData('campaigns'),StoreUtils.loadData('products'),StoreUtils.loadData('pickup-locations'),StoreUtils.loadMedia()]);
      const id=new URLSearchParams(location.search).get('id')||'wreaths-2026';const campaign=campaigns.find(item=>item.id===id);
      if(!campaign){host.innerHTML='<section class="page-section"><div class="wrap empty-state"><h1>Campaign not found</h1><a class="button" href="fundraising.html">Visit the Fundraising Center</a></div></section>';return;}
      const media=manifest.campaigns[mediaKey(campaign)]||manifest.campaigns['camp-cards'];const progress=campaign.progress||{};const percent=progress.goal?Math.min(100,Math.round(progress.raised/progress.goal*100)):0;const place=locations.find(item=>campaign.pickupLocationIds?.includes(item.id));const campaignProducts=products.filter(item=>item.campaignId===campaign.id);document.title=`${campaign.name} | Support Pack 321`;
      const gallery=media.gallery.filter(item=>item.publicApproved).map((item,index)=>`<figure><img src="${StoreUtils.escapeHtml(item.src)}" alt="${StoreUtils.escapeHtml(item.alt)}" width="900" height="675" loading="lazy" decoding="async"><figcaption>${index===0?'The Pack moments this campaign helps make possible.':'Real families, traditions, and adventures supported by our community.'}</figcaption></figure>`).join('');
      host.innerHTML=`<section class="campaign-hero"><div class="wrap campaign-hero-grid"><div><p class="eyebrow" style="color:#ffc72c">Current fundraiser</p><h1>${StoreUtils.escapeHtml(campaign.name)}</h1><p>${StoreUtils.escapeHtml(campaign.story||campaign.description)}</p><p><strong>${StoreUtils.formatDate(campaign.startDate)} – ${StoreUtils.formatDate(campaign.endDate)}</strong></p><div class="campaign-actions"><a class="button gold" href="#products">Shop Campaign</a><a class="button light" href="#story">Why It Matters</a></div></div><img src="${StoreUtils.escapeHtml(media.hero.src)}" alt="${StoreUtils.escapeHtml(media.hero.alt)}" width="1200" height="800" fetchpriority="high"></div></section>
      <section class="page-section soft-section"><div class="wrap"><div class="section-heading"><p class="eyebrow">Campaign progress</p><h2>Every order moves us forward</h2></div><div class="stat-grid">${stat(StoreUtils.formatCurrency((progress.raised||0)*100),'Raised')}${stat(`${percent}%`,'of our goal')}${stat(StoreUtils.formatCurrency((progress.goal||0)*100),'Goal')}${stat(progress.scoutsParticipating||0,'Scouts participating')}${stat(progress.daysRemaining??'—','Days remaining')}</div><div class="progress" aria-label="${percent}% of fundraising goal reached"><span style="width:${percent}%"></span></div><p style="text-align:center">${progress.orders||0} community orders and counting</p></div></section>
      <section class="page-section" id="story"><div class="wrap story-band"><p class="eyebrow" style="color:#ffc72c">Who you’re helping</p><h2>Fundraising turns into real Pack moments</h2><p>${StoreUtils.escapeHtml(campaign.description)} Your support helps fund camping, Pack traditions, awards, leader training, program supplies, and community events.</p></div></section>
      <section class="page-section"><div class="wrap"><div class="section-heading"><p class="eyebrow">Pack 321 stories</p><h2>What support makes possible</h2></div><div class="campaign-gallery">${gallery}</div></div></section>
      <section class="page-section soft-section" id="products"><div class="wrap"><div class="section-heading"><p class="eyebrow">Campaign products</p><h2>Choose your way to support</h2></div><div class="product-grid">${campaignProducts.map(item=>{const productMedia=manifest.products[item.id];return `<article class="product-card"><img src="${StoreUtils.escapeHtml(productMedia?.primary||item.image)}" alt="${StoreUtils.escapeHtml(item.name)}" width="600" height="450" loading="lazy"><div class="product-content"><h3>${StoreUtils.escapeHtml(item.name)}</h3><p>${StoreUtils.escapeHtml(item.description)}</p><div class="product-meta"><span>${StoreUtils.formatCurrency(item.price,item.currency)}</span></div><a class="button" href="product.html?id=${encodeURIComponent(item.id)}">View product</a></div></article>`;}).join('')}</div></div></section>
      <section class="page-section"><div class="wrap"><div class="contact-grid"><article class="contact-card"><h3>Volunteer moments</h3><p>Pack volunteers organize products, family communication, and pickup so campaign proceeds can stay focused on Scouts.</p></article><article class="contact-card" id="pickup"><h3>Pickup</h3><p><strong>${StoreUtils.escapeHtml(place?.name||'Location to be confirmed')}</strong><br>${StoreUtils.escapeHtml(campaign.pickupInstructions||place?.instructions||'Instructions will be emailed.')}</p></article><article class="contact-card"><h3>Questions?</h3><p>Our volunteer leaders can help with products, Scout support, or pickup.</p><a href="help.html#contact">Contact campaign support</a></article></div></div></section>
      <section class="page-section soft-section"><div class="wrap"><div class="section-heading"><h2>Campaign FAQ</h2></div><div class="faq-list">${(campaign.faq||[]).map(item=>`<details><summary>${StoreUtils.escapeHtml(item.question)}</summary><p>${StoreUtils.escapeHtml(item.answer)}</p></details>`).join('')||'<details><summary>How do I support this campaign?</summary><p>Choose a product or share the campaign with friends and family.</p></details>'}</div></div></section>`;
    }catch(error){console.error(error);host.innerHTML='<section class="page-section"><div class="wrap empty-state"><h1>Campaign details could not load</h1><p>Please refresh or visit the Fundraising Center.</p></div></section>';}
  });
})();
