(function(){
  'use strict';
  if(!document.querySelector('link[href$="store-v3-phase2.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/css/store-v3-phase2.css">');
  document.addEventListener('DOMContentLoaded',()=>document.body.classList.add('phase2-commerce-page','phase2-cart'),{once:true});
  document.addEventListener('DOMContentLoaded',async()=>{
    const host=document.querySelector('[data-cart]');if(!host)return;const U=StoreUtils;const [products,campaigns,manifest]=await Promise.all([U.loadData('products'),U.loadData('campaigns'),U.loadMedia()]);const productMap=Object.fromEntries(products.map(product=>[product.id,product]));const campaignMap=Object.fromEntries(campaigns.map(campaign=>[campaign.id,campaign]));
    function render(){const cart=U.readCart();let blocked=false;let subtotal=0;if(!cart.items.length){host.innerHTML='<div class="empty-state"><h1>Your cart is ready for adventure</h1><p>Add a fundraiser item or Pack merchandise to get started.</p><a class="button" href="shop.html">Browse products</a></div>';document.querySelector('[data-cart-summary]').hidden=true;return;}host.innerHTML=cart.items.map(item=>{const product=productMap[item.productId];const campaign=product?campaignMap[product.campaignId]:null;const available=U.isAvailable(product,campaign);if(!available)blocked=true;const line=product?product.price*item.quantity:0;subtotal+=line;const options=Object.entries(item.options||{}).filter(([,value])=>value).map(([key,value])=>`${key}: ${value}`).join(' · ');const support=item.attribution?.type==='scout'?item.attribution.value:item.attribution?.type==='none'?'No Scout selected':'Pack 321 generally';const image=manifest.products[product?.id]?.primary||product?.image||'assets/products/placeholder.svg';return `<article class="cart-item ${available?'':'is-unavailable'}"><img src="${U.escapeHtml(image)}" alt="${U.escapeHtml(product?.name||'Product')} product view" width="100" height="100"><div><h2>${U.escapeHtml(product?.name||'Product no longer available')}</h2>${campaign?`<p class="cart-meta">${U.escapeHtml(campaign.name)}</p>`:''}${options?`<p class="cart-meta">${U.escapeHtml(options)}</p>`:''}<p class="cart-meta">Supports: ${U.escapeHtml(support)}</p>${available?'':`<p class="inline-message error">Remove this item before checkout.</p>`}<div class="cart-controls"><button type="button" data-decrease="${U.escapeHtml(item.id)}" aria-label="Decrease quantity">−</button><strong>${item.quantity}</strong><button type="button" data-increase="${U.escapeHtml(item.id)}" aria-label="Increase quantity">+</button><button class="remove-button" type="button" data-remove="${U.escapeHtml(item.id)}">Remove</button></div></div><div class="cart-line"><span>${product?U.formatCurrency(product.price,product.currency):'—'} each</span><strong>${product?U.formatCurrency(line,product.currency):'—'}</strong></div></article>`;}).join('');const summary=document.querySelector('[data-cart-summary]');summary.hidden=false;summary.querySelector('[data-subtotal]').textContent=U.formatCurrency(subtotal);summary.querySelector('[data-total]').textContent=U.formatCurrency(subtotal);const checkout=summary.querySelector('[data-checkout-link]');checkout.classList.toggle('disabled',blocked);checkout.setAttribute('aria-disabled',String(blocked));checkout.href=blocked?'#':'checkout.html';}
    host.addEventListener('click',event=>{const action=event.target.closest('button');if(!action)return;const cart=U.readCart();const id=action.dataset.increase||action.dataset.decrease||action.dataset.remove;const item=cart.items.find(line=>line.id===id);if(!item)return;if(action.dataset.increase)item.quantity=Math.min(99,item.quantity+1);if(action.dataset.decrease)item.quantity=Math.max(1,item.quantity-1);if(action.dataset.remove!==undefined)cart.items=cart.items.filter(line=>line.id!==id);U.writeCart(cart);render();});render();
  });
})();
