(function(){
  'use strict';
  if(!document.querySelector('link[href$="store-v3-phase2.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/css/store-v3-phase2.css">');
  const overviewPage=location.pathname.split('/').pop()||'index.html';
  if(['index.html','fundraising.html'].includes(overviewPage))document.addEventListener('DOMContentLoaded',()=>document.body.classList.add('phase2-commerce-page','phase2-home'),{once:true});
  const U=()=>window.StoreUtils;
  let mediaManifest=null;
  const productDetailUrl=id=>U().getProductUrl(id);

  function campaignCard(c){
    const status=U().campaignStatus(c);const progress=c.progress||{};const percent=progress.goal?Math.min(100,Math.round(progress.raised/progress.goal*100)):0;const fullTitle=c.cardTitle||c.name;const statusLabel=status==='active'?'Active':status==='closed'?'Closed':'Coming Soon';const primary=c.renderer==='sponsorship-builder'?'Sponsor a Wreath':status==='active'?'Shop Campaign':status==='closed'?'View Results':'Preview Campaign';const url=U().getCampaignUrl(c);const aboutUrl=U().getCampaignUrl(c,{section:'about'});
    return `<article class="campaign-card" data-campaign-id="${U().escapeHtml(c.id)}"><div class="campaign-card__media"><a href="${U().escapeHtml(url)}" aria-label="View ${U().escapeHtml(fullTitle)}"><img src="${U().escapeHtml(c.cardImage||c.image)}" alt="${U().escapeHtml(c.cardImageAlt||fullTitle)}" width="800" height="800" loading="lazy"></a></div><div class="campaign-card__content"><div class="campaign-card__status"><span class="status-dot status-dot--${status==='active'?'active':'scheduled'}" aria-hidden="true"></span><span>${U().escapeHtml(statusLabel)}</span></div><h2 class="campaign-card__title"><a href="${U().escapeHtml(url)}">${U().escapeHtml(fullTitle)}</a></h2><p class="campaign-card__description">${U().escapeHtml(c.cardDescription||c.description)}</p><div class="campaign-card__progress" aria-label="Campaign progress"><div class="campaign-card__progress-track"><div class="campaign-card__progress-value" style="width:${percent}%"></div></div><p>${U().formatCurrency((progress.raised||0)*100)} of ${U().formatCurrency((progress.goal||0)*100)} goal · ${percent}%</p></div><div class="campaign-card__actions"><a class="button ${status==='active'?'':'outline'}" href="${U().escapeHtml(url)}">${primary} <span aria-hidden="true">→</span></a><a class="button outline" href="${U().escapeHtml(aboutUrl)}">Learn More</a></div></div></article>`;
  }

  function productCard(product,campaign){
    const noOptions=!product.options?.some(option=>option.required);const available=U().isAvailable(product,campaign);const priceLabel=product.priceStatus==='approved'&&Number(product.price)>0?U().formatCurrency(product.price,product.currency):'Pricing Pending';const label=campaign?`<p class="eyebrow">${U().escapeHtml(campaign.name)}</p>`:'';const media=mediaManifest?.products?.[product.id];
    const productUrl=productDetailUrl(product.id);
    return `<article class="product-card"><a class="product-card__media-link" href="${productUrl}" aria-label="View ${U().escapeHtml(product.name)}"><img src="${U().escapeHtml(media?.primary||product.image)}" data-hover-image="${U().escapeHtml(media?.hover||'')}" alt="${U().escapeHtml(product.name)} product view" width="600" height="450" loading="lazy"></a><div class="product-content">${label}<h3><a href="${productUrl}">${U().escapeHtml(product.name)}</a></h3><p>${U().escapeHtml(product.description)}</p><span class="sample-tag">Sample — not for sale</span><div class="product-meta"><span>${priceLabel}</span><span class="status ${available?'status-active':'status-unavailable'}">${available?'Available':'Preview only'}</span></div><div class="product-actions"><a class="button" href="${productUrl}">View product</a>${noOptions?`<button class="button gold" type="button" data-quick-add="${U().escapeHtml(product.id)}" ${available?'':'disabled'} aria-label="Quick add ${U().escapeHtml(product.name)}">+</button>`:''}</div></div></article>`;
  }

  function setupCatalog(products,campaigns,byCampaign,host){
    document.body.classList.add('phase2-commerce-page','phase2-shop');
    const search=document.querySelector('#search');const campaign=document.querySelector('#campaign-filter');const category=document.querySelector('#category-filter');const availability=document.querySelector('#availability-filter');const sort=document.querySelector('#sort');const count=document.querySelector('[data-result-count]');
    campaigns.filter(item=>!['closed','archived'].includes(U().campaignStatus(item))).forEach(item=>campaign.insertAdjacentHTML('beforeend',`<option value="${U().escapeHtml(item.id)}">${U().escapeHtml(item.name)}</option>`));
    [...new Set(products.map(product=>product.category))].sort().forEach(value=>category.insertAdjacentHTML('beforeend',`<option>${U().escapeHtml(value)}</option>`));
    const params=new URLSearchParams(location.search);const requested=params.get('campaign');if(requested)campaign.value=requested;const requestedCategory=params.get('category');if(requestedCategory)category.value=requestedCategory;const requestedType=params.get('type');const campaignLink=document.createElement('a');campaignLink.className='button outline campaign-filter-link';campaignLink.textContent='View Campaign';campaign.insertAdjacentElement('afterend',campaignLink);const updateCampaignLink=()=>{const selected=byCampaign[campaign.value];campaignLink.hidden=!selected;if(selected)campaignLink.href=U().getCampaignUrl(selected);};
    const panel=document.querySelector('.filter-panel');if(panel){panel.id='catalog-filters';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Product filters');const sortField=sort.closest('.form-field');if(sortField){sortField.querySelector('label')?.classList.remove('sr-only');panel.append(sortField);}document.querySelector('.catalog-layout')?.insertAdjacentHTML('beforebegin','<button class="button outline phase2-filter-toggle" type="button" aria-controls="catalog-filters" aria-expanded="false">Filters</button>');panel.insertAdjacentHTML('afterbegin','<button class="store-dialog__close phase2-filter-close" type="button" aria-label="Close filters">×</button>');const toggle=document.querySelector('.phase2-filter-toggle');let returnFocus=null;const close=restore=>{panel.classList.remove('is-open');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('filters-open');if(restore)(returnFocus||toggle)?.focus();};toggle?.addEventListener('click',()=>{returnFocus=document.activeElement;panel.classList.add('is-open');toggle.setAttribute('aria-expanded','true');document.body.classList.add('filters-open');panel.querySelector('input,select')?.focus();});panel.querySelector('.phase2-filter-close')?.addEventListener('click',()=>close(true));panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close(true);}});}
    function render(){let list=products.filter(product=>{const record=byCampaign[product.campaignId];const query=search.value.trim().toLowerCase();const availableProduct=U().isAvailable(product,record);return(!requestedType||requestedType!=='fundraiser'||Boolean(product.campaignId))&&(!query||product.name.toLowerCase().includes(query))&&(!campaign.value||product.campaignId===campaign.value)&&(!category.value||product.category===category.value)&&(!availability.value||(availability.value==='available'?availableProduct:!availableProduct));});list.sort((a,b)=>sort.value==='price-asc'?a.price-b.price:sort.value==='price-desc'?b.price-a.price:sort.value==='alpha'?a.name.localeCompare(b.name):Number(b.featured)-Number(a.featured));count.textContent=`${list.length} product${list.length===1?'':'s'}`;host.innerHTML=list.length?list.map(product=>productCard(product,byCampaign[product.campaignId])).join(''):'<div class="empty-state"><h2>No products match</h2><p>Try clearing a filter or using a different search.</p></div>';}
    [search,campaign,category,availability,sort].forEach(element=>element.addEventListener(element===search?'input':'change',()=>{render();if(element===campaign)updateCampaignLink();}));updateCampaignLink();render();
  }

  async function init(){
    const [products,campaigns,locations,media]=await Promise.all([U().loadData('products'),U().loadData('campaigns'),U().loadData('pickup-locations'),U().loadMedia()]);mediaManifest=media;const byCampaign=Object.fromEntries(campaigns.map(campaign=>[campaign.id,campaign]));
    const campaignHost=document.querySelector('[data-campaigns]');if(campaignHost){const featuredIds=['seroogy-candy-2026','popcorn-2026','rose-wreaths-2026','veterans-wreaths-2026','spring-2027','wreaths-2027'];const visible=featuredIds.map(id=>campaigns.find(campaign=>campaign.id===id)).filter(campaign=>campaign&&['active','scheduled','pricing-pending'].includes(U().campaignStatus(campaign)));campaignHost.innerHTML=visible.map(campaignCard).join('');}
    const pickup=document.querySelector('[data-pickup-info]');if(pickup){const active=campaigns.find(campaign=>U().campaignStatus(campaign)==='active');const place=locations.find(location=>active?.pickupLocationIds?.includes(location.id));pickup.innerHTML=`<strong>${U().escapeHtml(place?.name||'Campaign pickup')}</strong><br>${U().escapeHtml(active?.pickupInstructions||place?.instructions||'Pickup details will be provided with each campaign.')}`;}
    const featured=document.querySelector('[data-featured-products]');if(featured)featured.innerHTML=products.filter(product=>product.featured).map(product=>productCard(product,byCampaign[product.campaignId])).join('');
    const catalog=document.querySelector('[data-product-grid]');if(catalog)setupCatalog(products,campaigns,byCampaign,catalog);
    document.addEventListener('click',event=>{const button=event.target.closest('[data-quick-add]');if(!button)return;const product=products.find(item=>item.id===button.dataset.quickAdd);if(!product||!U().isAvailable(product,byCampaign[product.campaignId]))return;U().addCartItem({productId:product.id,quantity:1,options:{},attribution:null});U().showToast(`${product.name} added to cart.`);});
  }

  document.addEventListener('mouseover',event=>{const image=event.target.closest('[data-hover-image]');if(!image?.dataset.hoverImage)return;image.dataset.primaryImage=image.src;image.src=image.dataset.hoverImage;});
  document.addEventListener('mouseout',event=>{const image=event.target.closest('[data-hover-image]');if(image?.dataset.primaryImage)image.src=image.dataset.primaryImage;});
  document.addEventListener('DOMContentLoaded',()=>init().catch(error=>{console.error(error);document.querySelectorAll('[data-campaigns],[data-featured-products],[data-product-grid]').forEach(element=>element.innerHTML='<div class="empty-state"><h2>Store data could not load</h2><p>Run the store through a local web server and refresh.</p></div>');}));
})();
