(function(){
  'use strict';
  const U=()=>window.StoreUtils;
  function campaignCard(c){const status=U().campaignStatus(c);const p=c.progress||{};const percent=p.goal?Math.min(100,Math.round(p.raised/p.goal*100)):0;return `<article class="campaign-card"><img src="${U().escapeHtml(c.image)}" alt="Pack 321 adventure supported by ${U().escapeHtml(c.name)}" width="480" height="360"><div class="campaign-content"><span class="status status-${status}">${status==='scheduled'?'Coming Soon':U().escapeHtml(c.status)}</span><h3>${U().escapeHtml(c.name)}</h3><p>${U().escapeHtml(c.description)}</p><p class="campaign-dates">${U().formatDate(c.startDate)} – ${U().formatDate(c.endDate)}</p><div class="progress" aria-label="${percent}% of goal reached"><span style="width:${percent}%"></span></div><p class="campaign-dates"><strong>${percent}% toward ${U().formatCurrency((p.goal||0)*100)}</strong>${p.scoutsParticipating?` · ${p.scoutsParticipating} Scouts`:''}</p><div class="campaign-actions"><a class="button gold" href="campaign.html?id=${encodeURIComponent(c.id)}#products">Shop Campaign</a><a class="button outline" href="campaign.html?id=${encodeURIComponent(c.id)}">Learn More</a></div></div></article>`;}
  function productCard(p,campaign){const noOptions=!p.options?.some(o=>o.required);const available=U().isAvailable(p,campaign);const label=campaign?`<p class="eyebrow">${U().escapeHtml(campaign.name)}</p>`:'';return `<article class="product-card"><img src="${U().escapeHtml(p.image)}" alt="Placeholder artwork for ${U().escapeHtml(p.name)}" width="600" height="450" loading="lazy"><div class="product-content">${label}<h3>${U().escapeHtml(p.name)}</h3><p>${U().escapeHtml(p.description)}</p><span class="sample-tag">Sample — not for sale</span><div class="product-meta"><span>${U().formatCurrency(p.price,p.currency)}</span><span class="status ${available?'status-active':'status-unavailable'}">${available?'Available':'Preview only'}</span></div><div class="product-actions"><a class="button" href="product.html?id=${encodeURIComponent(p.id)}">View product</a>${noOptions?`<button class="button gold" type="button" data-quick-add="${U().escapeHtml(p.id)}" ${available?'':'disabled'} aria-label="Quick add ${U().escapeHtml(p.name)}">+</button>`:''}</div></div></article>`;}
  async function init(){const [products,campaigns,locations]=await Promise.all([U().loadData('products'),U().loadData('campaigns'),U().loadData('pickup-locations')]);const byCampaign=Object.fromEntries(campaigns.map(c=>[c.id,c]));
    const campaignHost=document.querySelector('[data-campaigns]');if(campaignHost){campaignHost.innerHTML=campaigns.filter(c=>['active','scheduled'].includes(U().campaignStatus(c))).map(campaignCard).join('');}
    const pickup=document.querySelector('[data-pickup-info]');if(pickup){const active=campaigns.find(c=>U().campaignStatus(c)==='active');const place=locations.find(l=>active?.pickupLocationIds?.includes(l.id));pickup.innerHTML=`<strong>${U().escapeHtml(place?.name||'Campaign pickup')}</strong><br>${U().escapeHtml(active?.pickupInstructions||place?.instructions||'Pickup details will be provided with each campaign.')}`;}
    const featured=document.querySelector('[data-featured-products]');if(featured){featured.innerHTML=products.filter(p=>p.featured).map(p=>productCard(p,byCampaign[p.campaignId])).join('');}
    const catalog=document.querySelector('[data-product-grid]');if(catalog){setupCatalog(products,campaigns,byCampaign,catalog);}
    document.addEventListener('click',e=>{const button=e.target.closest('[data-quick-add]');if(!button)return;const product=products.find(p=>p.id===button.dataset.quickAdd);if(!product||!U().isAvailable(product,byCampaign[product.campaignId]))return;U().addCartItem({productId:product.id,quantity:1,options:{},attribution:null});U().showToast(`${product.name} added to cart.`);});
  }
  function setupCatalog(products,campaigns,byCampaign,host){const search=document.querySelector('#search');const campaign=document.querySelector('#campaign-filter');const category=document.querySelector('#category-filter');const availability=document.querySelector('#availability-filter');const sort=document.querySelector('#sort');const count=document.querySelector('[data-result-count]');
    campaigns.filter(c=>!['closed','archived'].includes(U().campaignStatus(c))).forEach(c=>campaign.insertAdjacentHTML('beforeend',`<option value="${U().escapeHtml(c.id)}">${U().escapeHtml(c.name)}</option>`));[...new Set(products.map(p=>p.category))].sort().forEach(value=>category.insertAdjacentHTML('beforeend',`<option>${U().escapeHtml(value)}</option>`));const requested=new URLSearchParams(location.search).get('campaign');if(requested)campaign.value=requested;
    const params=new URLSearchParams(location.search);const requestedCategory=params.get('category');if(requestedCategory)category.value=requestedCategory;const requestedType=params.get('type');
    function render(){let list=products.filter(p=>{const c=byCampaign[p.campaignId];const query=search.value.trim().toLowerCase();const isAvailable=U().isAvailable(p,c);return(!requestedType||requestedType!=='fundraiser'||Boolean(p.campaignId))&&(!query||p.name.toLowerCase().includes(query))&&(!campaign.value||p.campaignId===campaign.value)&&(!category.value||p.category===category.value)&&(!availability.value||(availability.value==='available'?isAvailable:!isAvailable));});list.sort((a,b)=>sort.value==='price-asc'?a.price-b.price:sort.value==='price-desc'?b.price-a.price:sort.value==='alpha'?a.name.localeCompare(b.name):Number(b.featured)-Number(a.featured));count.textContent=`${list.length} product${list.length===1?'':'s'}`;host.innerHTML=list.length?list.map(p=>productCard(p,byCampaign[p.campaignId])).join(''):'<div class="empty-state"><h2>No products match</h2><p>Try clearing a filter or using a different search.</p></div>';}
    [search,campaign,category,availability,sort].forEach(el=>el.addEventListener(el===search?'input':'change',render));render();}
  document.addEventListener('DOMContentLoaded',()=>init().catch(error=>{console.error(error);document.querySelectorAll('[data-campaigns],[data-featured-products],[data-product-grid]').forEach(el=>el.innerHTML='<div class="empty-state"><h2>Store data could not load</h2><p>Run the store through a local web server and refresh.</p></div>');}));
})();
