(function(){
  'use strict';
  if(!document.querySelector('link[href$="store-v3-phase2.css"]'))document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/css/store-v3-phase2.css">');
  document.addEventListener('DOMContentLoaded',()=>document.body.classList.add('phase2-commerce-page','phase2-checkout'),{once:true});
  document.addEventListener('DOMContentLoaded',async()=>{
    const form=document.querySelector('[data-checkout-form]');if(!form)return;const U=StoreUtils;
    const [products,campaigns,locations]=await Promise.all([U.loadData('products'),U.loadData('campaigns'),U.loadData('pickup-locations')]);
    const productMap=Object.fromEntries(products.map(product=>[product.id,product]));const campaignMap=Object.fromEntries(campaigns.map(campaign=>[campaign.id,campaign]));let cart=U.readCart();const pickupIds=new Set();let subtotal=0;
    const summary=document.querySelector('[data-checkout-summary]');
    const pricing=document.querySelector('[data-checkout-pricing]');
    let attribution=cart.attribution||cart.items.find(item=>item.attribution)?.attribution;
    const renderSummary=nextCart=>{cart=nextCart;subtotal=0;pickupIds.clear();attribution=cart.attribution||cart.items.find(item=>item.attribution)?.attribution;const hasItems=cart.items.length>0;form.querySelectorAll('[data-checkout-next],[data-checkout-submit]').forEach(button=>button.disabled=!hasItems);if(!hasItems){summary.innerHTML='<div class="checkout-empty-summary"><p><strong>Your cart is empty.</strong></p><p>Browse products before beginning checkout.</p></div>';pricing.hidden=true;pricing.style.display='none';return;}summary.innerHTML=cart.items.map(item=>{const product=productMap[item.productId];if(!product)return'';subtotal+=product.price*item.quantity;campaignMap[product.campaignId]?.pickupLocationIds?.forEach(id=>pickupIds.add(id));return `<div class="summary-row"><span>${item.quantity} × ${U.escapeHtml(product.name)}</span><strong>${U.formatCurrency(product.price*item.quantity,product.currency)}</strong></div>`;}).join('');if(attribution?.type==='scout')summary.insertAdjacentHTML('afterbegin',`<div class="notice"><strong>Supporting: ${U.escapeHtml(attribution.displayName||'Pack 321 Scout')}</strong><br>Campaign and Scout attribution will be preserved through secure payment.</div>`);else summary.insertAdjacentHTML('afterbegin','<div class="notice"><strong>Supporting Pack 321 generally</strong><br>This order is not attributed to an individual Scout.</div>');document.querySelector('[data-checkout-total]').textContent=U.formatCurrency(subtotal);pricing.hidden=false;pricing.style.removeProperty('display');};
    renderSummary(cart);
    window.addEventListener('pack321:cart',event=>renderSummary(event.detail));
    window.addEventListener('storage',event=>{if(event.key==='pack321_store_cart_v1')renderSummary(U.readCart());});
    const pickup=document.querySelector('#pickup-location');locations.filter(location=>location.active&&(!pickupIds.size||pickupIds.has(location.id))).forEach(location=>pickup.insertAdjacentHTML('beforeend',`<option value="${U.escapeHtml(location.id)}">${U.escapeHtml(location.name)} — ${U.escapeHtml(location.city)}, ${U.escapeHtml(location.state)}</option>`));const requiresPickup=Pack321CheckoutPayload.requiresPickup(cart,products);if(cart.items.length&&!requiresPickup){const pickupStep=form.querySelector('[data-checkout-step="1"]');const pickupField=pickup.closest('.form-field');pickup.required=false;pickupField.hidden=true;pickupField.style.display='none';pickupStep.querySelector('h2').textContent='Fulfillment';pickupStep.querySelector('.notice').innerHTML='<strong>Program direct shipment</strong><br>These items are shipped directly through the fundraiser program. No local pickup or purchaser delivery is required.';form.querySelector('[data-checkout-step-button="1"]').textContent='2. Fulfillment';}
    form.addEventListener('submit',async event=>{event.preventDefault();const status=document.querySelector('[data-checkout-status]');const submit=form.querySelector('[data-checkout-submit]');const invalid=[...form.querySelectorAll('[required]')].find(element=>!element.checkValidity());if(invalid){status.textContent='Please complete all required fields and acknowledgments.';status.className='inline-message error';invalid.focus();return;}try{const payload={...Pack321CheckoutPayload.build({cart,products,contact:{firstName:form.firstName.value,lastName:form.lastName.value,email:form.email.value,phone:form.phone.value},pickupSelection:form.pickupLocation.value}),sourcePage:attribution?.sourcePage||location.pathname};window.dispatchEvent(new CustomEvent('pack321:checkout-payload-ready',{detail:payload}));const api=String(window.PACK321_API_BASE||'').replace(/\/$/,'');if(!api){status.textContent='Checkout API is not configured for this preview.';status.className='inline-message error';return;}let key=sessionStorage.getItem('pack321_checkout_key');if(!key){key=crypto.randomUUID().replaceAll('-','');sessionStorage.setItem('pack321_checkout_key',key);}submit.disabled=true;status.textContent='Opening secure Stripe Checkout…';status.className='inline-message';const response=await fetch(`${api}/api/checkout-sessions`,{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result.checkoutUrl)throw new Error('Secure checkout is temporarily unavailable. Please try again.');location.assign(result.checkoutUrl);}catch(error){submit.disabled=false;status.textContent=error.message||'Secure checkout is temporarily unavailable. Please try again.';status.className='inline-message error';}});
    const steps=[...form.querySelectorAll('[data-checkout-step]')];const stepButtons=[...form.querySelectorAll('[data-checkout-step-button]')];let currentStep=0;const showStep=index=>{currentStep=Math.max(0,Math.min(steps.length-1,index));steps.forEach((step,i)=>step.hidden=i!==currentStep);stepButtons.forEach((button,i)=>{if(i===currentStep)button.setAttribute('aria-current','step');else button.removeAttribute('aria-current');});steps[currentStep]?.querySelector('input,select,button')?.focus();};const validateStep=()=>{const invalid=[...steps[currentStep].querySelectorAll('[required]')].find(element=>!element.checkValidity());if(invalid){invalid.reportValidity();invalid.focus();return false;}return true;};form.addEventListener('click',event=>{if(event.target.closest('[data-checkout-next]')){if(validateStep())showStep(currentStep+1);}if(event.target.closest('[data-checkout-back]'))showStep(currentStep-1);const requested=event.target.closest('[data-checkout-step-button]');if(requested&&Number(requested.dataset.checkoutStepButton)<currentStep)showStep(Number(requested.dataset.checkoutStepButton));});form.addEventListener('invalid',event=>{const step=event.target.closest('[data-checkout-step]');if(step)showStep(Number(step.dataset.checkoutStep));},true);
    // Phase 2 server must reload products and campaigns, then validate prices, status, inventory, option IDs, pickup, and Scout eligibility before creating Stripe Checkout.
  });
})();
