(function(){
  'use strict';
  const impactCopy={camping:['Camping Adventures','Shared outdoor experiences build confidence and independence.'],pinewoodDerby:['Pinewood Derby','Creativity, craftsmanship, and good sportsmanship come together.'],service:['Community Service','Scouts learn responsibility by helping their neighbors.'],outdoorSkills:['Outdoor Skills','Hands-on practice turns curiosity into lifelong capability.'],recognition:['Recognition','Celebrating growth encourages every Scout to keep going.'],familyActivities:['Family Activities','Pack traditions create friendships for Scouts and grown-ups alike.'],hiking:['Leadership Development','The trail gives Scouts room to lead, listen, and persevere.'],blueGold:['Friendships','Pack celebrations connect families across every den.']};
  document.addEventListener('DOMContentLoaded',async()=>{try{const manifest=await StoreUtils.loadMedia();setupCarousel(manifest.homepageHero.filter(item=>item.publicApproved));renderImpact(manifest.events);}catch(error){console.error(error);}});
  function setupCarousel(slides){const root=document.querySelector('[data-media-carousel]');if(!root||!slides.length)return;let index=0;let paused=false;let timer=null;const image=root.querySelector('[data-hero-image]');const headline=root.querySelector('[data-hero-headline]');const statement=root.querySelector('[data-hero-statement]');const primary=root.querySelector('[data-hero-primary]');const secondary=root.querySelector('[data-hero-secondary]');const status=root.querySelector('[data-hero-status]');const dots=root.querySelector('[data-hero-dots]');slides.forEach((slide,i)=>dots.insertAdjacentHTML('beforeend',`<button type="button" data-hero-dot="${i}" aria-label="Show story ${i+1}: ${StoreUtils.escapeHtml(slide.headline)}"></button>`));
    const render=(next,announce=true)=>{index=(next+slides.length)%slides.length;const slide=slides[index];image.src=slide.src;image.srcset=slide.srcset||'';image.alt=slide.alt;image.width=1600;image.height=900;image.dataset.internalAttribution=slide.internalAttribution;image.onerror=()=>{image.onerror=null;image.src=slide.fallback;};headline.textContent=slide.headline;statement.textContent=slide.statement;primary.textContent=slide.primaryCta.label;primary.href=slide.primaryCta.href;secondary.textContent=slide.secondaryCta.label;secondary.href=slide.secondaryCta.href;dots.querySelectorAll('button').forEach((dot,i)=>{dot.classList.toggle('is-active',i===index);dot.setAttribute('aria-current',i===index?'true':'false');});if(announce)status.textContent=`Story ${index+1} of ${slides.length}: ${slide.headline}`;};
    const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const schedule=()=>{clearInterval(timer);if(!paused&&!reduced)timer=setInterval(()=>render(index+1,false),7000);};root.querySelector('[data-hero-prev]').addEventListener('click',()=>{render(index-1);schedule();});root.querySelector('[data-hero-next]').addEventListener('click',()=>{render(index+1);schedule();});dots.addEventListener('click',event=>{const button=event.target.closest('[data-hero-dot]');if(!button)return;render(Number(button.dataset.heroDot));schedule();});root.querySelector('[data-hero-pause]').addEventListener('click',event=>{paused=!paused;event.currentTarget.setAttribute('aria-pressed',String(paused));event.currentTarget.textContent=paused?'Resume rotation':'Pause rotation';schedule();});root.addEventListener('mouseenter',()=>clearInterval(timer));root.addEventListener('mouseleave',schedule);root.addEventListener('focusin',()=>clearInterval(timer));root.addEventListener('focusout',schedule);render(0,false);schedule();
  }
  function renderImpact(events){const host=document.querySelector('[data-impact-media]');if(!host)return;const order=['camping','pinewoodDerby','service','outdoorSkills','recognition','familyActivities','hiking','blueGold'];host.innerHTML=order.map(key=>{const media=events[key];const copy=impactCopy[key];return `<article class="impact-card"><img src="${StoreUtils.escapeHtml(media.src)}" alt="${StoreUtils.escapeHtml(media.alt)}" width="640" height="420" loading="lazy" decoding="async"><h3>${copy[0]}</h3><p>${copy[1]}</p></article>`;}).join('');}
})();
