(function(){
  'use strict';
  const CODE_PATTERN=/^[A-Z0-9]{6}$/;
  const publicActive=scout=>Boolean(scout&&scout.fundraisingEnabled&&scout.visibility==='public'&&scout.guardianApproved&&scout.status!=='expired');
  document.addEventListener('DOMContentLoaded',async()=>{
    const host=document.querySelector('[data-product-detail]');if(!host)return;const U=StoreUtils;
    try{
      const [products,campaigns,locations,manifest,scouts]=await Promise.all([U.loadData('products'),U.loadData('campaigns'),U.loadData('pickup-locations'),U.loadMedia(),U.loadData('scouts')]);
      const id=new URLSearchParams(location.search).get('id');const product=products.find(item=>item.id===id);
      if(!product){host.innerHTML='<div class="empty-state"><h1>Product not found</h1><p>This product may have moved or is no longer listed.</p><a class="button" href="shop.html">Return to shop</a></div>';return;}
      const campaign=campaigns.find(item=>item.id===product.campaignId);const pickup=locations.find(item=>campaign?.pickupLocationIds?.includes(item.id));const media=manifest.products[product.id]||{primary:product.image,gallery:product.images||[product.image],fallback:'/assets/products/placeholder.svg'};const gallery=[...new Set(media.gallery?.length?media.gallery:[media.primary])];
      const optionHtml=(product.options||[]).map(option=>`<div class="form-field"><label for="option-${U.escapeHtml(option.id)}">${U.escapeHtml(option.name)}${option.required?' *':''}</label><select id="option-${U.escapeHtml(option.id)}" data-option="${U.escapeHtml(option.id)}" data-required="${option.required}"><option value="">Choose ${U.escapeHtml(option.name.toLowerCase())}</option>${option.values.map(value=>`<option>${U.escapeHtml(value)}</option>`).join('')}</select></div>`).join('');
      const thumbs=gallery.map((src,index)=>`<button type="button" data-gallery-image="${U.escapeHtml(src)}" class="${index===0?'is-active':''}" aria-label="Show image ${index+1} of ${gallery.length}"><img src="${U.escapeHtml(src)}" alt="" width="78" height="78" loading="lazy"></button>`).join('');
      host.innerHTML=`<div class="product-gallery"><div class="product-gallery-main"><img src="${U.escapeHtml(media.primary)}" data-product-main alt="${U.escapeHtml(product.name)} product view" width="700" height="700" data-fallback="${U.escapeHtml(media.fallback)}"></div>${gallery.length>1?`<div class="product-thumbnails" aria-label="Product image gallery">${thumbs}</div>`:''}<p class="media-note">Hover or focus the main image to zoom. Additional approved photography can be added through the media manifest.</p></div><div class="product-info">${campaign?`<p class="eyebrow">${U.escapeHtml(campaign.name)}</p>`:''}<h1>${U.escapeHtml(product.name)}</h1><p class="product-price">${U.formatCurrency(product.price,product.currency)}</p><span class="sample-tag">Sample product — not for sale</span><p>${U.escapeHtml(product.description)}</p><div class="option-stack">${optionHtml}</div><fieldset><legend>Who would you like to support?</legend><label class="choice"><input type="radio" name="support" value="scout"> <span>Support a specific Scout</span></label><label class="choice"><input type="radio" name="support" value="pack" checked> <span>Support Pack 321 generally</span></label><div class="form-field" data-scout-field hidden><label for="scout-code">Fundraising code</label><input id="scout-code" autocomplete="off" autocapitalize="characters" maxlength="12"><small>Enter the code shared by the Scout or family. Name search is not available.</small></div></fieldset>${product.pickupRequired?`<div class="notice"><strong>Pickup information</strong><br>${U.escapeHtml(pickup?.name||'Location to be confirmed')} — ${U.escapeHtml(campaign?.pickupInstructions||pickup?.instructions||'Instructions will be provided.')}</div>`:''}<div class="quantity-row"><div class="form-field"><label for="quantity">Quantity</label><input id="quantity" type="number" min="1" max="99" value="1"></div><button class="button gold" type="button" data-add-product disabled>Add to cart</button></div><p class="inline-message" data-product-message></p><p><a href="shop.html">← Return to shopping</a></p></div>`;
      const mainImage=host.querySelector('[data-product-main]');mainImage.addEventListener('error',()=>{if(mainImage.src.endsWith(media.fallback))return;mainImage.src=media.fallback;});host.querySelector('.product-thumbnails')?.addEventListener('click',event=>{const button=event.target.closest('[data-gallery-image]');if(!button)return;mainImage.src=button.dataset.galleryImage;host.querySelectorAll('[data-gallery-image]').forEach(item=>item.classList.toggle('is-active',item===button));});
      const addButton=host.querySelector('[data-add-product]');addButton.disabled=!U.isAvailable(product,campaign);const message=host.querySelector('[data-product-message]');message.textContent=addButton.disabled?'This item is not currently available.':'Preview mode: item may be added for transaction testing; payment remains disabled.';const scoutField=host.querySelector('[data-scout-field]');host.querySelectorAll('[name=support]').forEach(radio=>radio.addEventListener('change',()=>{scoutField.hidden=host.querySelector('[name=support]:checked').value!=='scout';}));
      addButton.addEventListener('click',()=>{const missing=[...host.querySelectorAll('[data-required=true]')].find(element=>!element.value);if(missing){message.textContent=`Please choose ${missing.previousElementSibling.textContent.replace(' *','')}.`;message.className='inline-message error';missing.focus();return;}const existingContext=U.readAttribution();const support=existingContext?.type==='scout'?'scout':host.querySelector('[name=support]:checked').value;const code=(existingContext?.type==='scout'?existingContext.scoutCode:host.querySelector('#scout-code').value).trim().toUpperCase();if(support==='scout'&&!CODE_PATTERN.test(code)){message.textContent='Enter a valid six-character fundraising code.';message.className='inline-message error';host.querySelector('#scout-code').focus();return;}const scout=support==='scout'?scouts.find(item=>item.fundraisingCode===code):null;if(support==='scout'&&!publicActive(scout)){message.textContent='We could not find an active public fundraising page for that code.';message.className='inline-message error';host.querySelector('#scout-code').focus();return;}const attribution=support==='scout'?{...existingContext,type:'scout',value:scout.publicDisplayName,scoutCode:code,displayName:scout.publicDisplayName,campaignId:campaign?.id||existingContext?.campaignId||null,sourcePage:existingContext?.sourcePage||location.pathname,attributionSource:existingContext?.attributionSource||'product-code'}:{type:'pack',value:'Pack 321 generally',scoutCode:null,campaignId:campaign?.id||null,sourcePage:location.pathname,attributionSource:'pack-wide'};U.setAttribution(attribution);const options=Object.fromEntries([...host.querySelectorAll('[data-option]')].map(element=>[element.dataset.option,element.value]));U.addCartItem({productId:product.id,quantity:Number(host.querySelector('#quantity').value)||1,options,attribution});U.showToast(`${product.name} added to cart.`);});
    }catch(error){console.error('Product data unavailable',error);host.innerHTML='<div class="empty-state"><h1>Product data could not load</h1><p>Please refresh or return to the catalog.</p></div>';}
  });
})();
