(function(){
  'use strict';
  const StoreFocalImages={
    registry:{
      'camping.jpg':{x:'48%',y:'64%',tabletX:'48%',tabletY:'64%',mobileX:'50%',mobileY:'58%',ratio:'16 / 7',tabletRatio:'16 / 8',mobileRatio:'4 / 3'},
      'camping-640.f8beed81.webp':{x:'48%',y:'64%',tabletX:'48%',tabletY:'64%',mobileX:'50%',mobileY:'58%',ratio:'16 / 7',tabletRatio:'16 / 8',mobileRatio:'4 / 3'},
      'eagle-cave-640.37cef2da.webp':{x:'52%',y:'60%',tabletX:'52%',tabletY:'62%',mobileX:'52%',mobileY:'58%',ratio:'32 / 17',tabletRatio:'16 / 9',mobileRatio:'4 / 3'},
      'eagle-cave-360.9d80186c.webp':{x:'52%',y:'60%',tabletX:'52%',tabletY:'62%',mobileX:'52%',mobileY:'58%',ratio:'32 / 17',tabletRatio:'16 / 9',mobileRatio:'4 / 3'},
      'hiking.jpg':{x:'50%',y:'100%',tabletX:'50%',tabletY:'100%',mobileX:'50%',mobileY:'92%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1'},
      'hiking-640.70833d18.webp':{x:'50%',y:'100%',tabletX:'50%',tabletY:'100%',mobileX:'50%',mobileY:'92%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1'},
      'popcorn-fundraising-640.e05562b4.webp':{x:'52%',y:'52%',tabletX:'52%',tabletY:'52%',mobileX:'52%',mobileY:'50%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1',scale:'1.25',tabletScale:'1.2',mobileScale:'1.18'},
      'popcorn-fundraising-360.00123653.webp':{x:'52%',y:'52%',tabletX:'52%',tabletY:'52%',mobileX:'52%',mobileY:'50%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1',scale:'1.25',tabletScale:'1.2',mobileScale:'1.18'},
      'popcorn-fundraising-800.55b280bb.webp':{x:'52%',y:'52%',tabletX:'52%',tabletY:'52%',mobileX:'52%',mobileY:'50%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1',scale:'1.25',tabletScale:'1.2',mobileScale:'1.18'},
      'popcorn-fundraising-1200.256490e4.webp':{x:'52%',y:'52%',tabletX:'52%',tabletY:'52%',mobileX:'52%',mobileY:'50%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1',scale:'1.25',tabletScale:'1.2',mobileScale:'1.18'},
      'popcorn-fundraising-1800.aebee9f1.webp':{x:'52%',y:'52%',tabletX:'52%',tabletY:'52%',mobileX:'52%',mobileY:'50%',ratio:'16 / 9',tabletRatio:'4 / 3',mobileRatio:'1 / 1',scale:'1.25',tabletScale:'1.2',mobileScale:'1.18'},
      'blue-gold.jpg':{x:'58%',y:'58%',tabletX:'58%',tabletY:'58%',mobileX:'62%',mobileY:'56%'},
      'pinewood-derby.jpg':{x:'52%',y:'58%',tabletX:'52%',tabletY:'58%',mobileX:'54%',mobileY:'56%'},
      'graduation.jpg':{x:'50%',y:'61%',tabletX:'50%',tabletY:'61%',mobileX:'50%',mobileY:'58%'},
      'service.jpg':{x:'66%',y:'61%',tabletX:'66%',tabletY:'61%',mobileX:'68%',mobileY:'58%'},
      'fishing.jpg':{x:'34%',y:'57%',tabletX:'34%',tabletY:'57%',mobileX:'36%',mobileY:'55%'},
      'raingutter-regatta.jpg':{x:'50%',y:'45%',tabletX:'50%',tabletY:'45%',mobileX:'50%',mobileY:'42%'}
    },
    setVariables(element,values={}){const get=(key,fallback)=>element.dataset[key]||values[key]||fallback;[['--focal-x','focalX','x','50%'],['--focal-y','focalY','y','50%'],['--focal-x-tablet','focalXTablet','tabletX','50%'],['--focal-y-tablet','focalYTablet','tabletY','50%'],['--focal-x-mobile','focalXMobile','mobileX','50%'],['--focal-y-mobile','focalYMobile','mobileY','50%'],['--focal-ratio','focalRatio','ratio','16 / 7'],['--focal-ratio-tablet','focalRatioTablet','tabletRatio','16 / 9'],['--focal-ratio-mobile','focalRatioMobile','mobileRatio','4 / 3'],['--focal-scale','focalScale','scale','1'],['--focal-scale-tablet','focalScaleTablet','tabletScale','1'],['--focal-scale-mobile','focalScaleMobile','mobileScale','1']].forEach(([property,datasetKey,valueKey,fallback])=>element.style.setProperty(property,get(datasetKey,values[valueKey]||fallback)));},
    enhance(root=document){root.querySelectorAll?.('[data-focal-image],img,.help-hero-visual').forEach(element=>{const background=getComputedStyle(element).backgroundImage.match(/\/([^/'")]+\.(?:jpe?g|webp|png))/i)?.[1]||'';const source=element.currentSrc||element.getAttribute('src')||element.dataset.focalSrc||background;const key=source.split('/').pop()?.split('?')[0];const values=this.registry[key];if(!element.hasAttribute('data-focal-image')&&!values)return;element.dataset.focalImage=element.dataset.focalImage||(/IMG/i.test(element.tagName)?'media':'background');this.setVariables(element,values);});},
    init(){this.enhance();new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)this.enhance(node.matches?.('[data-focal-image],img')?(node.parentElement||document):node);}))).observe(document.body,{childList:true,subtree:true});}
  };
  window.StoreFocalImages=StoreFocalImages;
  const StoreShell={
    page:location.pathname.split('/').pop()||'index.html',
    active(files){return files.includes(this.page)?' aria-current="page"':'';},
    ensureAssets(){
      ['/css/revision-1.css','/css/revision-2.css','/css/revision-3.css','/css/revision-3-scout.css','/css/visual-regression.css','/css/grj-store-009.css','/css/store-v2.css','/css/store-v3-shell.css','/css/store-v3-1.css'].forEach(href=>{
        if(document.querySelector(`link[href="${href}"]`))return;const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link);
      });
      if(!document.querySelector('script[src="/js/code-search.js"]')){const script=document.createElement('script');script.src='/js/code-search.js';document.head.append(script);}
      if(this.page==='donations.html'&&!document.querySelector('script[src="/js/donations.js"]')){const script=document.createElement('script');script.src='/js/donations.js';document.head.append(script);}
    },
    placePageAssets(){
      if(!document.querySelector('[data-code-search]')&&this.page==='fundraising.html'){const section='<section class="page-section code-search-section" data-code-search></section>';document.querySelector('#scout-support')?.insertAdjacentHTML('afterend',section);}
      if(this.page==='fundraising.html'&&!document.querySelector('script[src="/js/fundraising-media.js"]')){const script=document.createElement('script');script.src='/js/fundraising-media.js';script.defer=true;document.head.append(script);}
    },
    header(){const active=files=>this.active(files);const chevron='<svg class="nav-chevron" viewBox="0 0 12 8" width="12" height="8" aria-hidden="true" focusable="false"><path d="M1 1.25 6 6.25l5-5" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"/></svg>';return `<header class="site-header" data-store-shell-header><div class="wrap header-inner"><a class="brand" href="/" aria-label="Support Pack 321 home"><img src="/assets/logos/cub-scout-logo.svg" alt="" width="56" height="56"><span class="brand-copy"><strong>Pack 321</strong><span>Support our adventures</span></span></a><button class="menu-toggle" type="button" data-menu-toggle aria-controls="store-nav" aria-expanded="false"><span aria-hidden="true">☰</span><span>Menu</span></button><nav class="nav" id="store-nav" data-store-nav aria-label="Store navigation" aria-hidden="false"><a${active(['index.html',''])} href="/">Store home</a><details class="nav-group"${active(['campaign.html','scout.html','find-a-scout.html','fundraising.html','donations.html'])?' data-current="true"':''}><summary aria-expanded="false">Fundraising ${chevron}</summary><div class="nav-menu"><a href="/fundraising.html#current">Current fundraisers</a><a${active(['find-a-scout.html'])} href="/find-a-scout.html">Find a Scout</a><a${active(['fundraising.html'])} href="/fundraising.html">Fundraising center</a><a${active(['donations.html'])} href="/donations.html">Donations</a></div></details><a${active(['shop.html','product.html'])} href="/shop.html">Shop</a><details class="nav-group"${active(['order-lookup.html','help.html'])?' data-current="true"':''}><summary aria-expanded="false">Help &amp; orders ${chevron}</summary><div class="nav-menu"><a${active(['order-lookup.html'])} href="/order-lookup.html">Order lookup</a><a${active(['help.html'])} href="/help.html">Help &amp; contact</a><a href="https://pack321wi.org/">Pack 321 website</a></div></details><a class="cart-link"${active(['cart.html','checkout.html'])} href="/cart.html" aria-label="Shopping cart">Cart <span class="cart-badge" data-cart-count>0</span></a></nav></div></header>`;},
    footer(){return `<footer class="site-footer store-footer" data-store-shell-footer><div class="wrap store-footer__inner"><p><strong>Pack 321 Store</strong> <span aria-hidden="true">·</span> Oak Creek, Wisconsin <span aria-hidden="true">·</span> Storefront preview</p><nav aria-label="Store footer"><a href="/help.html">Help</a><a href="/order-lookup.html">Order lookup</a><a href="https://pack321wi.org/#privacy">Privacy</a><a href="https://pack321wi.org/">Pack website</a></nav><p>© <span data-year></span> Cub Scout Pack 321</p></div></footer>`;},
    render(){
      this.ensureAssets();this.placePageAssets();document.body.classList.add('store-app');document.body.dataset.storePage=this.page.replace('.html','')||'home';StoreFocalImages.init();
      let header=document.querySelector('.site-header');if(!header){document.querySelector('.preview-banner')?.insertAdjacentHTML('afterend','<header class="site-header"></header>');header=document.querySelector('.site-header');}if(header)header.outerHTML=this.header();
      let footer=document.querySelector('.site-footer');if(!footer){document.body.insertAdjacentHTML('beforeend','<footer class="site-footer"></footer>');footer=document.querySelector('.site-footer');}if(footer)footer.outerHTML=this.footer();
    },
    bindNavigation(){const toggle=document.querySelector('[data-menu-toggle]'),nav=document.querySelector('[data-store-nav]');let returnFocus=null;const mobileQuery='(max-width: 1180px)';const focusable=()=>[...nav.querySelectorAll('a,summary,button')].filter(el=>!el.closest('[hidden]'));const close=restore=>{nav.classList.remove('is-open');nav.setAttribute('aria-hidden',matchMedia(mobileQuery).matches?'true':'false');toggle?.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');if(restore)(returnFocus||toggle)?.focus();};const open=()=>{returnFocus=document.activeElement;nav.classList.add('is-open');nav.setAttribute('aria-hidden','false');toggle.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');focusable()[0]?.focus();};toggle?.addEventListener('click',()=>nav.classList.contains('is-open')?close(true):open());nav?.addEventListener('click',event=>{if(event.target.closest('a'))close(false);});nav?.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();close(true);return;}if(event.key!=='Tab'||!nav.classList.contains('is-open'))return;const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});document.querySelectorAll('.nav-group').forEach(group=>group.addEventListener('toggle',()=>group.querySelector('summary')?.setAttribute('aria-expanded',String(group.open))));document.addEventListener('click',event=>{if(!event.target.closest('.nav-group'))document.querySelectorAll('.nav-group[open]').forEach(group=>group.removeAttribute('open'));});const media=matchMedia(mobileQuery);media.addEventListener?.('change',event=>{if(!event.matches){close(false);nav.setAttribute('aria-hidden','false');}else if(!nav.classList.contains('is-open'))nav.setAttribute('aria-hidden','true');});if(media.matches)nav?.setAttribute('aria-hidden','true');},
    bindTabs(){document.querySelectorAll('[data-store-tabs]').forEach(tablist=>{const tabs=[...tablist.querySelectorAll('[role="tab"]')];const select=tab=>tabs.forEach(item=>{const selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1;const panel=document.getElementById(item.getAttribute('aria-controls'));if(panel)panel.hidden=!selected;});tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>select(tab));tab.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();select(tabs[next]);});});});},
    bindDialogs(){document.addEventListener('click',event=>{const opener=event.target.closest('[data-dialog-open]');if(opener)document.getElementById(opener.dataset.dialogOpen)?.showModal();const closer=event.target.closest('[data-dialog-close]');if(closer)closer.closest('dialog')?.close();});document.querySelectorAll('dialog[data-store-dialog],dialog[data-store-drawer]').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();}));}
    ,bindProductCardLinks(){const enhance=root=>root.querySelectorAll?.('.product-card').forEach(card=>{const existing=card.querySelector('a[href*="product.html?id="]');if(!existing)return;const id=new URL(existing.href,location.href).searchParams.get('id');if(!id)return;const href=StoreUtils.getProductUrl(id);const image=card.querySelector(':scope > img,.product-card__image');if(image&&!image.closest('a')){const link=document.createElement('a');link.className='product-card__media-link';link.href=href;link.setAttribute('aria-label',`View ${card.querySelector('h3')?.textContent.trim()||'product'}`);image.before(link);link.append(image);}const heading=card.querySelector('h3');if(heading&&!heading.querySelector('a')){const link=document.createElement('a');link.href=href;link.textContent=heading.textContent;heading.replaceChildren(link);}existing.href=href;});enhance(document);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)enhance(node);}))).observe(document.body,{childList:true,subtree:true});}
  };
  async function hydrateAttribution(){const params=new URLSearchParams(location.search);if(params.get('support')==='pack'){const cart=StoreUtils.readCart();const attribution={type:'pack',value:'Pack 321 generally',scoutCode:null,campaignId:null,sourcePage:location.pathname,attributionSource:'pack-wide',timestamp:new Date().toISOString()};StoreUtils.clearAttribution();cart.attribution=attribution;cart.items=cart.items.map(item=>({...item,attribution}));StoreUtils.writeCart(cart);return;}const code=params.get('scout');if(!code)return;try{const scouts=await StoreUtils.loadData('scouts');const scout=scouts.find(item=>item.fundraisingCode===code.toUpperCase()&&item.fundraisingEnabled&&item.visibility==='public'&&item.guardianApproved);if(scout)StoreUtils.setAttribution({type:'scout',scoutCode:scout.fundraisingCode,displayName:scout.publicDisplayName,campaignId:params.get('campaign')||params.get('id'),sourcePage:location.pathname,attributionSource:'scout-link',timestamp:new Date().toISOString()});}catch(error){console.error('Unable to restore Scout attribution.',error);}}
  function renderSupportContext(){document.querySelector('.support-context')?.remove();const context=StoreUtils.readAttribution();if(context?.type!=='scout'||!context.displayName)return;const url=new URL(location.href);url.searchParams.delete('scout');url.searchParams.set('support','pack');const banner=document.createElement('div');banner.className='support-context';banner.innerHTML=`<div class="wrap support-context__inner"><strong>Supporting ${StoreUtils.escapeHtml(context.displayName)}</strong><a data-clear-support href="${StoreUtils.escapeHtml(url.pathname+url.search)}">Change to Pack-wide support</a><details><summary aria-label="How Scout attribution works">How support works</summary><p>Scout attribution follows this order through checkout.</p></details></div>`;document.querySelector('.site-header')?.insertAdjacentElement('afterend',banner);}
  window.StoreShell=StoreShell;
  document.addEventListener('DOMContentLoaded',()=>{StoreShell.render();StoreShell.bindNavigation();StoreShell.bindTabs();StoreShell.bindDialogs();StoreShell.bindProductCardLinks();hydrateAttribution().then(renderSupportContext);window.addEventListener('pack321:attribution',renderSupportContext);StoreUtils.updateCartBadge();document.querySelectorAll('[data-year]').forEach(el=>{el.textContent=new Date().getFullYear();});});
})();
